package com.tide.journal;

import android.app.*;import android.content.*;import android.content.pm.*;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;
import com.tide.journal.data.*;import com.tide.journal.domain.*;import com.tide.journal.sync.AlertJob;import com.tide.journal.ui.*;
import org.json.*;import java.time.Instant;import java.util.*;import java.util.concurrent.*;
import static com.tide.journal.ui.Ui.*;

/** All screens are Android views. Data and scene state never run in a web runtime. */
public final class MainActivity extends Activity {
 private Repository repo;private SharedPreferences prefs;private final Handler main=new Handler(Looper.getMainLooper());
 private LinearLayout root,body,nav;private ScrollView scroll;private TextView status,quote,quoteMeta,reading,interpretation;private CandleChart chart;private SpatialLesson scene;
 private int tab,generation,stage;private String coin="BTC",period="4h",reportPeriod="daily",etfCoin="BTC",lessonId="",reportId="";private boolean active,refreshing,expanded;
 private long multiAt,reportAt;private final Map<String,TextView> periodViews=new LinkedHashMap<>();private final List<Future<?>> pending=new ArrayList<>();
 private JSONObject reports,lesson;private JSONArray catalog;private Lessons.Result result;private TextView control,lessonStep;private final List<TextView>numbers=new ArrayList<>();
 interface Work<T>{T run()throws Exception;}interface Done<T>{void accept(T v);}
 private final Runnable tick=new Runnable(){public void run(){if(!active)return;if(tab==0)refreshMarket(false);else if(tab==1&&reportId.isEmpty()&&System.currentTimeMillis()-reportAt>60000)loadReports();main.postDelayed(this,15000);}};
 @Override public void onCreate(Bundle state){super.onCreate(state);repo=Repository.get(this);prefs=AlertJob.prefs(this);AlertJob.channel(this);try{catalog=new JSONArray(repo.asset("lessons.json"));}catch(Exception e){catalog=new JSONArray();}
  if(state!=null){tab=state.getInt("tab");coin=state.getString("coin","BTC");period=state.getString("period","4h");lessonId=state.getString("lesson","");stage=state.getInt("stage");}else tab=getIntent().getIntExtra("tab",0);
  getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
  if(Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(0,()->goBack());
  root=column(this);root.setBackgroundColor(BG);setContentView(root);if(Build.VERSION.SDK_INT>=30)root.setOnApplyWindowInsetsListener((v,in)->{android.graphics.Insets s=in.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());v.setPadding(s.left,s.top,s.right,s.bottom);return in;});
  LinearLayout top=row(this);top.setPadding(dp(this,22),dp(this,12),dp(this,22),dp(this,8));TextView brand=heading(this,"观潮  /  TIDE",20);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));status=text(this,"NATIVE · 06",10,MUTED);top.addView(status);root.addView(top);
  scroll=new ScrollView(this);scroll.setFillViewport(false);scroll.setClipToPadding(false);body=column(this);body.setPadding(dp(this,18),dp(this,16),dp(this,18),dp(this,24));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));nav=row(this);nav.setPadding(dp(this,8),dp(this,8),dp(this,8),dp(this,8));root.addView(nav);render();AlertJob.schedule(this);
 }
 @Override protected void onSaveInstanceState(Bundle b){b.putInt("tab",tab);b.putString("coin",coin);b.putString("period",period);b.putString("lesson",lessonId);b.putInt("stage",stage);super.onSaveInstanceState(b);}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);tab=i.getIntExtra("tab",tab);render();}
 @Override protected void onResume(){super.onResume();active=true;if(scene!=null)scene.resumeScene();main.removeCallbacks(tick);main.post(tick);requestSmoothDisplay();}
 @Override protected void onPause(){active=false;main.removeCallbacks(tick);if(scene!=null)scene.pauseScene();super.onPause();}
 @Override protected void onDestroy(){generation++;for(Future<?>f:pending)f.cancel(true);main.removeCallbacksAndMessages(null);super.onDestroy();}
 private void requestSmoothDisplay(){Display d=getWindowManager().getDefaultDisplay();Display.Mode current=d.getMode(),best=current;for(Display.Mode m:d.getSupportedModes())if(m.getPhysicalWidth()==current.getPhysicalWidth()&&m.getPhysicalHeight()==current.getPhysicalHeight()&&m.getRefreshRate()>best.getRefreshRate()&&m.getRefreshRate()<=144)best=m;WindowManager.LayoutParams p=getWindow().getAttributes();p.preferredDisplayModeId=best.getModeId();getWindow().setAttributes(p);}
 @Override public void onBackPressed(){goBack();}private void goBack(){if(!lessonId.isEmpty()){lessonId="";render();}else if(!reportId.isEmpty()){reportId="";render();}else if(tab!=0){tab=0;render();}else finish();}
 private <T>void task(Work<T>w,Done<T>d,Done<String>error){int g=generation;pending.removeIf(Future::isDone);Future<?>f=repo.io.submit(()->{try{T value=w.run();main.post(()->{if(g==generation&&!isDestroyed())d.accept(value);});}catch(Exception e){String msg=e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();main.post(()->{if(g==generation&&!isDestroyed())error.accept(msg);});}});pending.add(f);}
 private void render(){generation++;refreshing=false;for(Future<?>f:pending)f.cancel(true);pending.clear();if(scene!=null){scene.pauseScene();scene=null;}body.removeAllViews();nav.removeAllViews();numbers.clear();periodViews.clear();String[]names={"行情","研报","课堂","资金","提醒"};for(int i=0;i<names.length;i++){final int t=i;weighted(nav,button(this,names[i],tab==i,()->{tab=t;lessonId="";reportId="";render();}));}scroll.scrollTo(0,0);
  switch(tab){case 0:market();break;case 1:if(reportId.isEmpty())reports();else reportDetail();break;case 2:if(lessonId.isEmpty())lessons();else lesson();break;case 3:flows();break;case 4:alerts();break;}
 }
 private void intro(String tag,String title,String sub){body.addView(text(this,tag,11,MUTED));gap(body,8);body.addView(heading(this,title,30));gap(body,8);body.addView(text(this,sub,14,MUTED));gap(body,22);}
 private LinearLayout panel(String title){LinearLayout c=card(this);if(!title.isEmpty()){c.addView(heading(this,title,19));gap(c,10);}body.addView(c);return c;}
 private void para(LinearLayout c,String s){if(s==null||s.isEmpty()||s.equals("null"))return;TextView t=text(this,s,14,INK);t.setTextIsSelectable(true);c.addView(t);gap(c,10);}
 private void chips(LinearLayout into,String[]values,String selected,Done<String>click){HorizontalScrollView h=new HorizontalScrollView(this);h.setHorizontalScrollBarEnabled(false);LinearLayout r=row(this);for(String v:values){TextView b=button(this,label(v),v.equals(selected),()->click.accept(v));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.rightMargin=dp(this,6);r.addView(b,p);}h.addView(r);into.addView(h);gap(into,12);}
 private String label(String v){switch(v){case "1h":return"1 小时";case "4h":return"4 小时";case "8h":return"8 小时";case "12h":return"12 小时";case "1d":return"日线";case "1w":return"周线";case "daily":return"每日研究";case "weekly":return"每周研究";default:return v;}}
 private void link(LinearLayout c,String title,String url){if(url==null||!url.startsWith("https://"))return;c.addView(button(this,title+" ↗",false,()->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(ActivityNotFoundException e){Toast.makeText(this,"未安装浏览器",Toast.LENGTH_SHORT).show();}}));gap(c,8);}
 private String string(JSONObject j,String key){return j==null||j.isNull(key)?"":j.optString(key,"");}
 private void expand(LinearLayout c,String title,String detail){TextView text=text(this,detail,14,INK);text.setTextIsSelectable(true);text.setVisibility(View.GONE);c.addView(button(this,title+"  ＋",false,()->text.setVisibility(text.getVisibility()==View.GONE?View.VISIBLE:View.GONE)));c.addView(text);gap(c,8);}
 private String join(JSONArray a){if(a==null)return"";StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++)s.append(i==0?"":"\n").append("• ").append(a.optString(i));return s.toString();}

 private void market(){intro("MARKET OBSERVATORY","看清变化的结构。","价格、动量与闭合确认，放在同一个时间窗口。",false);}
 private void intro(String a,String b,String c,boolean unused){intro(a,b,c);chips(body,new String[]{"BTC","ETH","SOL"},coin,v->{coin=v;multiAt=0;render();});LinearLayout q=panel(coin+" / USDT");quote=heading(this,"—",38);q.addView(quote);quoteMeta=text(this,"正在核对交易所时间与数据…",12,MUTED);q.addView(quoteMeta);gap(q,18);chips(q,Market.PERIODS,period,v->{period=v;render();});reading=text(this,"选中 K 线后，数值会出现在这里。",12,MUTED);reading.setTextIsSelectable(true);chart=new CandleChart(this,(bar,p)->reading.setText((bar.closed?"已闭合":"形成中 · 不用于确认")+"  "+time(bar.openAt)+"\nO "+n(bar.open)+"   H "+n(bar.high)+"   L "+n(bar.low)+"   C "+n(bar.close)+"\nVOL "+n(bar.volume)+" "+coin+"\nBB20  上 "+n(p.upper)+"  中 "+n(p.middle)+"  下 "+n(p.lower)+"\nMACD  DIF "+n(p.dif)+"  DEA "+n(p.dea)+"  柱 "+n(p.hist)+"\nRSI14  "+n(p.rsi)));
  q.addView(chart,new LinearLayout.LayoutParams(-1,dp(this,440)));LinearLayout controls=row(this);weighted(controls,button(this,"缩小",false,()->chart.zoom(1.3f)));weighted(controls,button(this,"放大",false,()->chart.zoom(.77f)));weighted(controls,button(this,"最新闭合",false,()->chart.latest()));q.addView(controls);Switch bands=new Switch(this);bands.setText("布林带 20 · 2");bands.setMinHeight(dp(this,48));bands.setChecked(true);bands.setOnCheckedChangeListener((v,on)->chart.bands(on));q.addView(bands);q.addView(reading);
  LinearLayout d=panel(label(period)+" · 收盘解读");interpretation=text(this,"等待确认数据…",15,INK);interpretation.setTextIsSelectable(true);d.addView(interpretation);gap(d,12);expand(d,"指标怎么读？","BB 使用 20 根收盘、总体标准差与 2 倍带宽。MACD 为 12/26/9，EMA 使用 SMA 种子，柱体 = DIF − DEA；某些平台显示 2 倍柱值。RSI14 使用 Wilder 平滑。\n\n数字默认取最近已闭合线，点击形成中的线会明确标识。价格指标同属一个证据家族，不能单独宣布牛熊转换。单根突破是候选；两根闭合保持同一箱体边界，也不代表已完成回踩。");d.addView(button(this,"重新获取",false,()->refreshMarket(true)));
  LinearLayout multi=panel("把不同周期放在一起");para(multi,"每个周期独立计算，日线与小时线可以出现分歧。");for(String p:Market.PERIODS){TextView t=button(this,label(p)+" · 等待更新",false,()->{period=p;render();});multi.addView(t);gap(multi,6);periodViews.put(p,t);}LinearLayout deriv=panel("杠杆温度");TextView out=text(this,"原生持仓量与资金费分开看；数据来自 Binance USDT 永续。",14,MUTED);deriv.addView(out);gap(deriv,12);deriv.addView(button(this,"读取 OI 与资金费",false,()->{out.setText("正在读取…");task(()->repo.derivatives(coin),j->{JSONObject oi=j.optJSONObject("oi"),f=j.optJSONObject("funding");out.setText("原生 OI  "+n(oi.optDouble("openInterest"))+" "+coin+"\n资金费  "+n(f.optDouble("lastFundingRate")*100)+"%\n下次结算  "+time(f.optLong("nextFundingTime"))+"\n来源时间  "+time(oi.optLong("time"))+"\n未做跨所汇总；美元 OI 不等同于原生 OI。");},e->out.setText("来源暂不可用："+e));}));refreshMarket(true);
 }
 private void refreshMarket(boolean force){if(refreshing||tab!=0)return;refreshing=true;String c=coin,p=period;task(()->repo.bars(c,p),b->{refreshing=false;Market.Bar last=b.bars.get(b.bars.size()-1);quote.setText(n(last.close));quoteMeta.setText((b.cached?"历史缓存":"Binance 现货快照")+" · "+time(b.asOf)+"\n前台约 15 秒更新 · 最新价可能来自形成中 K 线");chart.data(b.bars,b.points);interpretation.setText(explain(b.analysis));status.setText(b.cached?"缓存 · 暂停信号":"来源已响应");},e->{refreshing=false;quoteMeta.setText("暂未获得报价 · "+e);status.setText("等待来源");interpretation.setText("当前数据不可用，暂停判读。");});long now=System.currentTimeMillis();if(force||now-multiAt>60000){multiAt=now;for(String pp:Market.PERIODS){TextView v=periodViews.get(pp);task(()->repo.bars(c,pp),b->{if(v!=null)v.setText(label(pp)+"  ·  "+(b.analysis.valid()?b.analysis.trend+"\n"+b.analysis.structure:b.analysis.reason));},e->{if(v!=null)v.setText(label(pp)+" · 来源不可用");});}}}
 private String explain(Market.Analysis a){if(!a.valid())return a.reason+"\n缓存与未闭合数据不产生新信号。";return a.trend+"\n"+a.structure+"\n确认时间  "+time(a.closedAt)+"\n\n"+a.candle+"；相对前收盘 "+String.format(Locale.US,"%+.2f%%",a.change)+"\n相对前 20 根成交量："+n(a.volumeRatio)+" 倍\n\nMACD · "+a.macdText+"\n\nRSI · "+a.rsiText+(a.box==null?"":"\n\n固定箱体 "+n(a.box.low)+" — "+n(a.box.high))+"\n\n价格形态不代表机制健康或个人买卖许可。";}

 private LinearLayout reportList;private void reports(){intro("RESEARCH JOURNAL","把信息，连成理解。","读最新一期，也保留当时的证据和反证。");chips(body,new String[]{"daily","weekly"},reportPeriod,v->{reportPeriod=v;render();});LinearLayout c=panel("从这段对话到手机");para(c,"在维护观潮的这个项目里分析 BTC，再加一句“更新”。助手核验并发布新一期后，这里自动读取，不用复制或导入。未发布前，不会凭空生成一份日报。");c.addView(button(this,"检查云端新一期",false,()->loadReports()));reportList=column(this);body.addView(reportList);loadReports();}
 private void loadReports(){reportAt=System.currentTimeMillis();task(()->repo.document("reports"),p->{reports=p.data;if(reportList==null)return;reportList.removeAllViews();TextView state=text(this,p.state+" · revision "+reports.optString("revision")+(p.issue.isEmpty()?"":"\n云端请求失败："+p.issue),11,MUTED);reportList.addView(state);gap(reportList,12);JSONArray a=reports.optJSONArray("reports");if(a!=null)for(int i=a.length()-1;i>=0;i--){JSONObject r=a.optJSONObject(i);if(r==null||!r.optString("period").equals(reportPeriod))continue;LinearLayout c=card(this);c.addView(text(this,r.optString("date")+" · "+(r.optString("kind").equals("market")?"市场研究":"方法 / 使用指南"),11,MUTED));gap(c,10);c.addView(heading(this,r.optString("title"),23));gap(c,10);para(c,r.optString("summary"));String id=r.optString("id");c.addView(button(this,"打开这一期  →",false,()->{reportId=id;render();}));reportList.addView(c);}},e->{if(reportList!=null){reportList.removeAllViews();reportList.addView(text(this,"报告读取失败："+e,14,RED));}});}
 private JSONObject find(JSONArray a,String id){if(a!=null)for(int i=0;i<a.length();i++){JSONObject j=a.optJSONObject(i);if(j!=null&&j.optString("id").equals(id))return j;}return null;}
 private boolean has(JSONArray a,String id){if(a!=null)for(int i=0;i<a.length();i++)if(a.optString(i).equals(id))return true;return false;}
 private void reportDetail(){JSONObject r=reports==null?null:find(reports.optJSONArray("reports"),reportId);if(r==null){reportId="";reports();return;}body.addView(button(this,"← 所有研究",false,()->{reportId="";render();}));gap(body,14);intro(r.optString("edition"),r.optString("title"),r.optString("summary"));LinearLayout meta=panel("这期的适用范围");para(meta,string(r,"notice"));String until=string(r,"validUntil");if(!until.isEmpty())try{para(meta,(Instant.parse(until).toEpochMilli()<System.currentTimeMillis()?"已到复核期限 · ":"复核期限 · ")+until);}catch(Exception e){para(meta,"复核时间格式异常，暂不作为当前判断。");}para(meta,"发布时间："+(string(r,"publishedAt").isEmpty()?"方法资料，无行情发布时间":r.optString("publishedAt")));
  JSONArray take=r.optJSONArray("takeaways");if(take!=null)for(int i=0;i<take.length();i++){JSONObject t=take.optJSONObject(i);if(t!=null){LinearLayout c=panel(t.optString("title"));para(c,t.optString("text"));}}
  JSONArray sections=r.optJSONArray("sections");if(sections!=null)for(int i=0;i<sections.length();i++){JSONObject t=sections.optJSONObject(i);if(t!=null){LinearLayout c=panel(t.optString("title"));para(c,t.optString("body"));para(c,"来源 · "+t.optString("source"));}}
  JSONArray assets=r.optJSONArray("assets");if(assets!=null)for(int i=0;i<assets.length();i++){JSONObject a=assets.optJSONObject(i);if(a==null)continue;LinearLayout c=panel(a.optString("symbol"));para(c,"趋势 · "+a.optString("trend")+"\n健康 · "+a.optString("health")+"\n风险 · "+a.optString("risk"));para(c,a.optString("action"));expand(c,"证据与缺口",join(a.optJSONArray("evidence"))+"\n\n缺失\n"+join(a.optJSONArray("missing")));para(c,"失效 / 复核 · "+a.optString("invalidation")+"\n"+a.optString("nextReview"));}
  JSONArray events=reports.optJSONArray("events");if(events!=null)for(int i=0;i<events.length();i++){JSONObject e=events.optJSONObject(i);if(e==null||!has(r.optJSONArray("events"),e.optString("id")))continue;LinearLayout c=panel(e.optString("title"));para(c,e.optString("status"));para(c,e.optString("why"));expand(c,"拆开检查",join(e.optJSONArray("checklist")));JSONArray scenarios=e.optJSONArray("scenarios");if(scenarios!=null)for(int k=0;k<scenarios.length();k++){JSONObject s=scenarios.optJSONObject(k);if(s!=null)expand(c,s.optString("label")+" · "+s.optString("title"),s.optString("body")+"\n"+s.optString("watch"));}}
  LinearLayout qa=panel("就这份报告，继续理解");para(qa,"检索本期引用的解释卡。这里没有连接实时 AI，也不会编造当前市场数据。");EditText input=new EditText(this);input.setHint("例如：RSI、健康度、持仓量");input.setSingleLine(true);qa.addView(input);LinearLayout answers=column(this);JSONArray knowledge=reports.optJSONArray("knowledge");Runnable search=()->{answers.removeAllViews();String query=input.getText().toString().trim().toLowerCase(Locale.ROOT);int hits=0;if(knowledge!=null)for(int i=0;i<knowledge.length();i++){JSONObject k=knowledge.optJSONObject(i);if(k==null||!has(r.optJSONArray("qa"),k.optString("id")))continue;String searchable=k.toString().toLowerCase(Locale.ROOT);if(!query.isEmpty()&&!searchable.contains(query))continue;expand(answers,k.optString("question",k.optString("title")),k.optString("answer",k.optString("body")));hits++;}if(hits==0)para(answers,"本期没有匹配的解释。可以回到对话继续问，并要求更新。");};qa.addView(button(this,"查找解释",false,search));qa.addView(answers);search.run();LinearLayout end=panel("反证与下一步");para(end,r.optString("counterEvidence"));para(end,r.optString("nextReview"));JSONArray src=r.optJSONArray("sources");if(src!=null)for(int i=0;i<src.length();i++){JSONObject s=src.optJSONObject(i);if(s==null)continue;para(end,s.optString("title")+"\n"+s.optString("status")+"\n"+string(s,"observedAt"));link(end,"查看来源",string(s,"url"));}
 }

 private void lessons(){intro("SPATIAL CLASSROOM","让抽象，变得可触碰。","拖动参数、拆开模型，亲手看看一件事怎样发生。");LinearLayout h=panel("一个数字，会怎样传导？");para(h,"9 个小实验 · 每次约 2 分钟\n所有参数都是明确的教学假设，数值可以展开核算。");for(int i=0;i<catalog.length();i++){JSONObject l=catalog.optJSONObject(i);if(l==null)continue;LinearLayout c=panel(String.format(Locale.US,"%02d  /  ",i+1)+l.optString("title"));para(c,l.optString("subtitle"));c.addView(button(this,"进入实验  →",false,()->{lessonId=l.optString("id");stage=0;expanded=false;render();}));}}
 private void lesson(){lesson=find(catalog,lessonId);if(lesson==null){lessonId="";lessons();return;}body.addView(button(this,"← 全部课堂",false,()->{lessonId="";render();}));gap(body,12);intro("A SMALL EXPERIMENT",lesson.optString("title"),lesson.optString("subtitle"));LinearLayout c=panel("用手改变一个条件");para(c,lesson.optString("setup"));ActivityManager am=(ActivityManager)getSystemService(ACTIVITY_SERVICE);if(am.getDeviceConfigurationInfo().reqGlEsVersion>=0x20000){scene=new SpatialLesson(this,i->modelDetail(i));scene.reduce(prefs.getBoolean("reduce",false));c.addView(scene,new LinearLayout.LayoutParams(-1,dp(this,310)));if(active)scene.resumeScene();}else para(c,"此设备不支持三维渲染，下面仍可完整操作与核算。");control=text(this,"",14,INK);gap(c,12);c.addView(control);double min=lesson.optDouble("min"),max=lesson.optDouble("max"),step=lesson.optDouble("step",1);SeekBar slider=new SeekBar(this);slider.setMax((int)Math.round((max-min)/step));slider.setMinHeight(dp(this,48));slider.setContentDescription(lesson.optString("control"));double value=prefs.getFloat("lesson_"+lessonId,(float)lesson.optDouble("value"));value=Math.max(min,Math.min(max,value));slider.setProgress((int)Math.round((value-min)/step));c.addView(slider);slider.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}public void onProgressChanged(SeekBar s,int p,boolean user){double value=min+p*step;updateLesson(value);if(user)prefs.edit().putFloat("lesson_"+lessonId,(float)value).apply();}});
  LinearLayout values=column(this);for(int i=0;i<3;i++){final int index=i;TextView t=button(this,"",false,()->modelDetail(index));numbers.add(t);values.addView(t);gap(values,6);}c.addView(values);c.addView(button(this,"展开 / 合拢模型",false,()->{expanded=!expanded;if(scene!=null)scene.expanded(expanded);}));gap(c,8);para(c,"可左右旋转、点选模型。三种颜色与下面三项数值一一对应，零值位于网格，负值在网格下方。");updateLesson(value);
  LinearLayout steps=panel("把过程拆成四步");lessonStep=text(this,"",16,INK);steps.addView(lessonStep);gap(steps,14);LinearLayout controls=row(this);weighted(controls,button(this,"上一步",false,()->{stage=Math.max(0,stage-1);updateStage();}));weighted(controls,button(this,"下一步",false,()->{stage=Math.min(3,stage+1);updateStage();}));steps.addView(controls);updateStage();link(steps,"延伸阅读",lesson.optString("source"));
 }
 private void updateLesson(double value){result=Lessons.calculate(lessonId,value);control.setText(lesson.optString("control")+"  "+n(value)+lesson.optString("unit"));for(int i=0;i<numbers.size();i++)numbers.get(i).setText(result.labels[i]+"     "+n(result.values[i])+" "+result.unit);if(scene!=null)scene.values(result);}
 private void updateStage(){JSONArray steps=lesson.optJSONArray("stages");if(steps==null||steps.length()==0)return;stage=Math.max(0,Math.min(stage,steps.length()-1));JSONObject s=steps.optJSONObject(stage);lessonStep.setText((stage+1)+" / "+steps.length()+"\n\n"+s.optString("title")+"\n\n"+s.optString("body")+"\n\n"+s.optString("caveat"));}
 private void modelDetail(int i){if(result==null)return;new AlertDialog.Builder(this).setTitle(result.labels[i]).setMessage(n(result.values[i])+" "+result.unit+"\n\n"+result.formula+"\n\n教学模型，不是实时经济或币价预测。").setPositiveButton("明白了",null).show();}

 private void flows(){intro("FLOW & EXPECTATIONS","资金往哪里去？","先对齐产品、交易日和单位，再看净流向。");chips(body,new String[]{"BTC","ETH","SOL"},etfCoin,v->{etfCoin=v;render();});LinearLayout c=panel("美国现货 ETF · 每日净流");TextView state=text(this,"正在读取云端披露快照…",12,MUTED);c.addView(state);LinearLayout rows=column(this);c.addView(rows);task(()->repo.document("etf-snapshot"),p->{state.setText(p.state+"\n采集时间 "+p.data.optString("capturedAt")+"\n单位：百万美元 · 有日期快照，非实时接口"+(p.issue.isEmpty()?"":"\n云端失败："+p.issue));JSONObject asset=p.data.optJSONObject("assets").optJSONObject(etfCoin);JSONArray data=asset.optJSONArray("rows");if(data!=null)for(int i=data.length()-1;i>=Math.max(0,data.length()-10);i--){JSONObject row=data.optJSONObject(i);if(row==null)continue;String flow=row.isNull("total")?"待披露":String.format(Locale.US,"%+.1f",row.optDouble("total"));gap(rows,8);rows.addView(button(this,row.optString("date")+"     "+flow+(row.optString("status").equals("complete")?"":" · 部分"),false,()->{StringBuilder b=new StringBuilder("单位：百万美元\n");JSONArray fs=row.optJSONArray("funds");if(fs!=null)for(int k=0;k<fs.length();k++){JSONObject f=fs.optJSONObject(k);if(f!=null)b.append("\n").append(f.optString("ticker")).append("   ").append(f.isNull("flow")?"未披露":n(f.optDouble("flow")));}new AlertDialog.Builder(this).setTitle(etfCoin+" · "+row.optString("date")).setMessage(b.toString()).setPositiveButton("完成",null).show();}));}gap(rows,12);link(rows,"Farside 原始披露表",asset.optString("source"));link(rows,"CoinGlass 对照页",asset.optString("compare"));},e->state.setText("ETF 数据不可用："+e));
  LinearLayout explain=panel("净流量，不是成交量");para(explain,"先看同交易日整体，再拆基金贡献。未披露保留空缺；周末不虚构新交易日。AUM 会随价格波动，不能直接当成申购资金。");explain.addView(button(this,"进入 ETF 互动课堂",false,()->{tab=2;lessonId="etf";stage=0;render();}));LinearLayout pred=panel("市场正在押注什么？");para(pred,"预测市场报价与利率期货隐含定价属于不同口径。这里读取 Polymarket 活跃议题，不把报价当确定概率。");LinearLayout results=column(this);pred.addView(button(this,"读取预测市场议题",false,()->{results.removeAllViews();para(results,"正在读取…");task(()->repo.predictions(),a->{results.removeAllViews();if(a.length()==0)para(results,"当前返回列表内没有匹配议题。");for(int i=0;i<Math.min(12,a.length());i++){JSONObject m=a.optJSONObject(i);if(m==null)continue;String details=m.optString("description")+"\n截止："+m.optString("endDate")+"\n读取时间："+time(System.currentTimeMillis());try{JSONArray o=m.opt("outcomes") instanceof JSONArray?m.getJSONArray("outcomes"):new JSONArray(m.optString("outcomes"));JSONArray prices=m.opt("outcomePrices") instanceof JSONArray?m.getJSONArray("outcomePrices"):new JSONArray(m.optString("outcomePrices"));if(o.length()!=prices.length())throw new Exception();for(int k=0;k<o.length();k++){double price=prices.getDouble(k);if(!Double.isFinite(price)||price<0||price>1)throw new Exception();details+="\n"+o.getString(k)+" · 报价 "+n(price*100)+"¢";}}catch(Exception e){details+="\n报价字段不完整，不显示概率。";}expand(results,m.optString("question"),details);link(results,"核对市场与结算规则","https://polymarket.com/event/"+Uri.encode(m.optString("slug")));}},e->{results.removeAllViews();para(results,"来源不可用："+e);});}));pred.addView(results);link(pred,"CME FedWatch · 官方说明","https://www.cmegroup.com/markets/interest-rates/cme-fedwatch-tool.html");
 }

 private void alerts(){intro("NOTIFICATION CENTER","重要变化，留个提醒。","确认闭合、记录依据，也明确这次有没有送达。");LinearLayout c=panel("系统通知与后台检查");Switch enable=new Switch(this);enable.setText("启用行情与研究提醒");enable.setMinHeight(dp(this,52));enable.setChecked(prefs.getBoolean("alerts",false));c.addView(enable);enable.setOnCheckedChangeListener((b,on)->{if(on&&Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},41);enable.setChecked(false);return;}prefs.edit().putBoolean("alerts",on).putLong("enabledAt",System.currentTimeMillis()).apply();AlertJob.schedule(this);});para(c,"系统当前通知权限："+(AlertJob.allowed(this)?"已允许":"未允许")+"\n后台由 Android 安排，最短约 15 分钟；省电、离线或强制停止可能延迟。当前是设备检查，不是全天候即时云推送。");String[][]types={{"structure","箱体突破与保持"},{"move","单根收盘涨跌 ≥ 3%"},{"indicator","MACD 交叉 / RSI 进入极值"},{"close","每根 1h / 4h 闭合"},{"report","新发布的市场研究"}};for(String[]type:types){Switch s=new Switch(this);s.setText(type[1]);s.setMinHeight(dp(this,48));s.setChecked(prefs.getBoolean("type_"+type[0],!type[0].equals("close")));s.setOnCheckedChangeListener((b,on)->prefs.edit().putBoolean("type_"+type[0],on).apply());c.addView(s);}gap(c,10);c.addView(button(this,"检查一次后台任务",false,()->Toast.makeText(this,AlertJob.once(this)?"已交给系统调度，稍后刷新记录":"请先启用提醒",Toast.LENGTH_LONG).show()));gap(c,8);c.addView(button(this,"发送本机测试通知",false,()->{if(!AlertJob.allowed(this)){if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},42);return;}String id="test:"+System.currentTimeMillis();repo.store.add(id,"观潮测试通知","设备已成功调用 Android 通知服务；不是行情信号。",System.currentTimeMillis());AlertJob.notification(this,id,"观潮测试通知","这是一条本机测试通知。");repo.store.mark(id);Toast.makeText(this,"测试通知已提交系统",Toast.LENGTH_SHORT).show();}));
  LinearLayout log=panel("最近一次检查");para(log,"开始："+time(prefs.getLong("lastAttempt",0))+"\n来源响应："+time(prefs.getLong("lastResponse",0))+"\n全周期成功："+time(prefs.getLong("lastSuccess",0))+"\n"+prefs.getString("lastResult","还没有检查记录"));log.addView(button(this,"刷新检查记录",false,()->render()));Switch reduce=new Switch(this);reduce.setMinHeight(dp(this,48));reduce.setText("减少课堂动态效果");reduce.setChecked(prefs.getBoolean("reduce",false));reduce.setOnCheckedChangeListener((b,on)->prefs.edit().putBoolean("reduce",on).apply());log.addView(reduce);LinearLayout inbox=panel("提醒收件箱");List<String[]> notices=repo.store.notices();if(notices.isEmpty())para(inbox,"暂时没有符合条件的新事件。开启之前的旧信号不会补推。");for(String[]v:notices)expand(inbox,v[1]+" · "+time(Long.parseLong(v[3])),v[2]+"\n"+(v[4].equals("1")?"已交给系统通知服务":"仅记录，未提交系统通知"));
 }
 @Override public void onRequestPermissionsResult(int code,String[]p,int[]r){super.onRequestPermissionsResult(code,p,r);if(code==41&&r.length>0&&r[0]==PackageManager.PERMISSION_GRANTED){prefs.edit().putBoolean("alerts",true).putLong("enabledAt",System.currentTimeMillis()).apply();AlertJob.schedule(this);}if(tab==4)render();}
}
