package com.tide.journal;

import android.app.*;import android.content.*;import android.content.pm.*;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;
import com.tide.journal.data.*;import com.tide.journal.domain.*;import com.tide.journal.sync.AlertJob;import com.tide.journal.sync.WatchService;import com.tide.journal.ui.*;
import org.json.*;import java.time.Instant;import java.util.*;import java.util.concurrent.*;
import static com.tide.journal.ui.Ui.*;

/** All screens are Android views. Data and view state never run in a web runtime. */
public final class MainActivity extends Activity {
 private Repository repo;private SharedPreferences prefs;private final Handler main=new Handler(Looper.getMainLooper());
 private LinearLayout root,body,nav;private ScrollView scroll;private TextView status,quote,quoteChange,quoteMeta,reading,interpretation;private CandleChart chart;
 private int tab,generation,etfLimit=30,quoteToken,etfRequestGeneration;private String coin="BTC",period="4h",reportPeriod="daily",etfCoin="BTC",lessonId="",reportId="",etfRange="全部";private boolean active,refreshing,quoteRefreshing,reportsRefreshing,etfRefreshing,resumeNeedsRender;private int restoreScrollY=-1;
 private long multiAt,reportAt,chartAt,etfAt,lastQuoteAt;private Future<?> quoteRequest;private final Map<String,TextView> periodViews=new LinkedHashMap<>();private final List<Future<?>> pending=new ArrayList<>();
 private JSONObject reports,etfData;private JSONArray catalog;private LinearLayout etfRows;private TextView etfState,etfSummary;private FlowChart flowChart;
 interface Work<T>{T run()throws Exception;}interface Done<T>{void accept(T v);}
 private final Runnable tick=new Runnable(){public void run(){if(!active)return;if(tab==0){refreshQuote();if(System.currentTimeMillis()-chartAt>=15000){chartAt=System.currentTimeMillis();refreshMarket(false);}}else if(tab==1&&reportId.isEmpty()&&System.currentTimeMillis()-reportAt>60000)loadReports();else if(tab==3&&System.currentTimeMillis()-etfAt>300000)loadEtf();main.postDelayed(this,3000);}};
 @Override public void onCreate(Bundle state){super.onCreate(state);Ui.configure(this);repo=Repository.get(this);prefs=AlertJob.prefs(this);AlertJob.channel(this);try{catalog=new JSONArray(repo.asset("explainers.json"));}catch(Exception e){catalog=new JSONArray();}
  coin=prefs.getString("coin","BTC");period=prefs.getString("period","4h");etfCoin=prefs.getString("etfCoin","BTC");etfRange=prefs.getString("etfRange","全部");
  if(state!=null){tab=state.getInt("tab");coin=state.getString("coin","BTC");period=state.getString("period","4h");lessonId=state.getString("lesson","");etfCoin=state.getString("etfCoin","BTC");etfRange=state.getString("etfRange","全部");reportPeriod=state.getString("reportPeriod","daily");reportId=state.getString("reportId","");etfLimit=state.getInt("etfLimit",30);restoreScrollY=state.getInt("scrollY",0);String savedReports=state.getString("reports","");try{if(!savedReports.isEmpty())reports=new JSONObject(savedReports);}catch(JSONException ignored){reportId="";}}else tab=getIntent().getIntExtra("tab",0);
  if(tab<0||tab>4)tab=0;if(!Arrays.asList("BTC","ETH","SOL").contains(coin))coin="BTC";if(!Arrays.asList(Market.PERIODS).contains(period))period="4h";
  getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(SURFACE);getWindow().getDecorView().setSystemUiVisibility(isDark()?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
  if(Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(0,()->goBack());
  setContentView(R.layout.screen_shell);root=findViewById(R.id.app_shell);scroll=findViewById(R.id.page_scroll);body=findViewById(R.id.page_body);nav=findViewById(R.id.page_nav);status=findViewById(R.id.source_status);
  if(Build.VERSION.SDK_INT>=30)root.setOnApplyWindowInsetsListener((v,in)->{android.graphics.Insets s=in.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());v.setPadding(s.left,s.top,s.right,s.bottom);return in;});
  render();restoreScroll();AlertJob.schedule(this);
 }
 @Override protected void onSaveInstanceState(Bundle b){b.putInt("tab",tab);b.putString("coin",coin);b.putString("period",period);b.putString("lesson",lessonId);b.putString("etfCoin",etfCoin);b.putString("etfRange",etfRange);b.putString("reportPeriod",reportPeriod);b.putString("reportId",reportId);b.putInt("etfLimit",etfLimit);b.putInt("scrollY",scroll.getScrollY());if(reports!=null&&reports.toString().length()<=100000)b.putString("reports",reports.toString());super.onSaveInstanceState(b);}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);tab=i.getIntExtra("tab",tab);if(tab<0||tab>4)tab=0;lessonId="";reportId="";restoreScrollY=-1;render();}
 @Override protected void onResume(){super.onResume();active=true;quoteRefreshing=false;if(resumeNeedsRender){resumeNeedsRender=false;render();restoreScroll();}main.removeCallbacks(tick);main.post(tick);}
 @Override protected void onPause(){active=false;restoreScrollY=scroll.getScrollY();resumeNeedsRender=true;generation++;main.removeCallbacks(tick);for(Future<?> f:pending)f.cancel(true);pending.clear();if(quoteRequest!=null)quoteRequest.cancel(true);quoteToken++;refreshing=quoteRefreshing=reportsRefreshing=etfRefreshing=false;prefs.edit().putString("coin",coin).putString("period",period).putString("etfCoin",etfCoin).putString("etfRange",etfRange).apply();super.onPause();}
 @Override protected void onDestroy(){generation++;quoteToken++;if(quoteRequest!=null)quoteRequest.cancel(true);for(Future<?>f:pending)f.cancel(true);main.removeCallbacksAndMessages(null);super.onDestroy();}
 private void restoreScroll(){if(restoreScrollY<0)return;if(tab==1&&reportId.isEmpty()&&(reportList==null||reportList.getChildCount()==0))return;if(tab==3&&etfData==null)return;final int y=restoreScrollY,g=generation;restoreScrollY=-1;scroll.getViewTreeObserver().addOnPreDrawListener(new ViewTreeObserver.OnPreDrawListener(){public boolean onPreDraw(){if(scroll.getViewTreeObserver().isAlive())scroll.getViewTreeObserver().removeOnPreDrawListener(this);if(g==generation&&!isDestroyed())scroll.scrollTo(0,y);return true;}});}
 @Override public void onBackPressed(){goBack();}private void goBack(){if(!lessonId.isEmpty()){lessonId="";render();}else if(!reportId.isEmpty()){reportId="";render();}else if(tab!=0){tab=0;render();}else finish();}
 private <T>void task(Work<T>w,Done<T>d,Done<String>error){int g=generation;pending.removeIf(Future::isDone);Future<?>f=HttpRequests.submit(repo.io,()->{try{T value=w.run();main.post(()->{if(g==generation&&!isDestroyed())try{d.accept(value);}catch(Exception e){error.accept(e.getMessage()==null?"数据显示失败，请重试":e.getMessage());}});}catch(Exception e){String msg=e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();main.post(()->{if(g==generation&&!isDestroyed())error.accept(msg);});}});pending.add(f);}
 private void render(){generation++;refreshing=reportsRefreshing=etfRefreshing=false;for(Future<?>f:pending)f.cancel(true);pending.clear();if(quoteRequest!=null)quoteRequest.cancel(true);quoteToken++;quoteRefreshing=false;body.removeAllViews();nav.removeAllViews();etfData=null;etfRows=null;lastQuoteAt=0;periodViews.clear();String[]names={"行情","研报","看懂","ETF","提醒"};for(int i=0;i<names.length;i++){final int t=i;weighted(nav,new NavItem(this,i,names[i],tab==i,()->{tab=t;lessonId="";reportId="";restoreScrollY=-1;render();}));}status.setText(tab==0?"市场观察":names[tab]);scroll.scrollTo(0,0);
  switch(tab){case 0:market();break;case 1:if(reportId.isEmpty())reports();else reportDetail();break;case 2:if(lessonId.isEmpty())lessons();else lesson();break;case 3:flows();break;case 4:alerts();break;}
 }
 private void intro(String tag,String title,String sub){TextView eyebrow=text(this,tag+"  /  GUANCHAO",11,BLUE);eyebrow.setLetterSpacing(.1f);body.addView(eyebrow);gap(body,8);body.addView(heading(this,title,28));gap(body,8);body.addView(text(this,sub,14,MUTED));gap(body,18);}
 private LinearLayout panel(String title){LinearLayout c=card(this);if(!title.isEmpty()){c.addView(heading(this,title,19));gap(c,10);}body.addView(c);return c;}
 private void para(LinearLayout c,String s){if(s==null||s.isEmpty()||s.equals("null"))return;TextView t=text(this,s,15,INK);t.setTextIsSelectable(true);c.addView(t);gap(c,10);}
 private void chips(LinearLayout into,String[]values,String selected,Done<String>click){HorizontalScrollView h=new HorizontalScrollView(this);h.setHorizontalScrollBarEnabled(false);LinearLayout r=row(this);for(String v:values){boolean interval=Arrays.asList(Market.PERIODS).contains(v);TextView b=button(this,interval&&v.endsWith("h")?v:label(v),v.equals(selected),()->{for(int i=0;i<r.getChildCount();i++)selectButton((TextView)r.getChildAt(i),values[i].equals(v));restoreScrollY=-1;click.accept(v);});if(interval){b.setTextSize(13);b.setMinWidth(dp(this,48));b.setPadding(dp(this,7),dp(this,8),dp(this,7),dp(this,8));b.setContentDescription(label(v));}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.rightMargin=dp(this,v.equals(values[values.length-1])?0:interval?4:6);r.addView(b,p);}h.addView(r);into.addView(h);gap(into,12);}
 private String label(String v){switch(v){case "1h":return"1 小时";case "4h":return"4 小时";case "8h":return"8 小时";case "12h":return"12 小时";case "1d":return"日线";case "1w":return"周线";case "daily":return"每日研究";case "weekly":return"每周研究";default:return v;}}
 private void link(LinearLayout c,String title,String url){if(url==null||!url.startsWith("https://"))return;c.addView(button(this,title+" ↗",false,()->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(ActivityNotFoundException e){Toast.makeText(this,"未安装浏览器",Toast.LENGTH_SHORT).show();}}));gap(c,8);}
 private String string(JSONObject j,String key){return j==null||j.isNull(key)?"":j.optString(key,"");}
 private void expand(LinearLayout c,String title,String detail){TextView text=text(this,detail,14,INK);text.setPadding(dp(this,4),dp(this,12),dp(this,4),dp(this,12));text.setTextIsSelectable(true);text.setVisibility(View.GONE);TextView toggle=button(this,title+"  ＋",false,()->{});toggle.setOnClickListener(v->{boolean show=text.getVisibility()==View.GONE;text.setVisibility(show?View.VISIBLE:View.GONE);toggle.setText(title+(show?"  −":"  ＋"));});c.addView(toggle);c.addView(text);gap(c,8);}
 private String join(JSONArray a){if(a==null)return"";StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++)s.append(i==0?"":"\n").append("• ").append(a.optString(i));return s.toString();}

 private void market(){intro("市场","行情","价格、趋势和风险，放在一起看。",false);}
 private void intro(String a,String b,String c,boolean unused){body.addView(text(this,c,13,MUTED));gap(body,12);chips(body,new String[]{"BTC","ETH","SOL"},coin,v->{coin=v;multiAt=0;render();});LinearLayout q=panel(coin+"  /  USDT");quote=heading(this,"—",42);quote.setSingleLine(true);quote.setAutoSizeTextTypeUniformWithConfiguration(24,42,1,android.util.TypedValue.COMPLEX_UNIT_SP);quote.setGravity(Gravity.CENTER_VERTICAL);q.addView(quote,new LinearLayout.LayoutParams(-1,dp(this,56)));gap(q,6);quoteChange=text(this,"24h —",14,MUTED);quoteChange.setPadding(dp(this,10),dp(this,6),dp(this,10),dp(this,6));quoteChange.setBackground(shape(SURFACE2,10,this));quoteMeta=text(this,"正在获取报价…",11,MUTED);quoteMeta.setGravity(Gravity.END);LinearLayout meta=row(this);meta.addView(quoteChange,new LinearLayout.LayoutParams(-2,-2));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(0,-2,1);mp.leftMargin=dp(this,10);meta.addView(quoteMeta,mp);q.addView(meta);gap(q,12);chips(q,Market.PERIODS,period,v->{period=v;render();});reading=text(this,"选中 K 线后，数值会出现在这里。",12,MUTED);reading.setTextIsSelectable(true);chart=new CandleChart(this,(bar,p)->reading.setText((bar.closed?"已闭合":"形成中 · 不用于确认")+"  "+time(bar.openAt)+"\nO "+n(bar.open)+"   H "+n(bar.high)+"   L "+n(bar.low)+"   C "+n(bar.close)+"\nVOL "+n(bar.volume)+" "+coin+"\nBB20  上 "+n(p.upper)+"  中 "+n(p.middle)+"  下 "+n(p.lower)+"\nMACD  DIF "+n(p.dif)+"  DEA "+n(p.dea)+"  柱 "+n(p.hist)+"\nRSI14  "+n(p.rsi)));
  chart.onPick(()->new AlertDialog.Builder(this).setTitle("K 线与指标数值").setMessage(reading.getText()).setPositiveButton("完成",null).show());q.addView(chart,new LinearLayout.LayoutParams(-1,dp(this,getResources().getConfiguration().fontScale>1.15f?280:300)));LinearLayout controls=row(this);weighted(controls,button(this,"缩小",false,()->chart.zoom(1.3f)));weighted(controls,button(this,"放大",false,()->chart.zoom(.77f)));TextView latest=button(this,"最新",false,()->chart.latest());latest.setContentDescription("回到最新闭合 K 线");weighted(controls,latest);q.addView(controls);Switch bands=new Switch(this);bands.setText("布林带 20 · 2");bands.setMinHeight(dp(this,48));bands.setChecked(true);bands.setOnCheckedChangeListener((v,on)->chart.bands(on));bands.setTextColor(INK);q.addView(bands);reading.setVisibility(View.GONE);TextView details=button(this,"查看 K 线与指标数值  ∨",false,()->{});details.setOnClickListener(v->{boolean open=reading.getVisibility()!=View.VISIBLE;reading.setVisibility(open?View.VISIBLE:View.GONE);details.setText(open?"收起数值  ∧":"查看 K 线与指标数值  ∨");});q.addView(details);gap(q,8);q.addView(reading);
  LinearLayout d=panel(label(period)+" · 收盘解读");interpretation=text(this,"等待确认数据…",15,INK);interpretation.setTextIsSelectable(true);interpretation.setMaxLines(5);interpretation.setEllipsize(android.text.TextUtils.TruncateAt.END);d.addView(interpretation);gap(d,12);TextView reasoning=button(this,"展开完整解读",false,()->{});reasoning.setOnClickListener(v->{boolean open=interpretation.getMaxLines()!=Integer.MAX_VALUE;interpretation.setMaxLines(open?Integer.MAX_VALUE:5);interpretation.setEllipsize(open?null:android.text.TextUtils.TruncateAt.END);reasoning.setText(open?"收起解读":"展开完整解读");});d.addView(reasoning);gap(d,12);expand(d,"指标怎么读？","BB 使用 20 根收盘、总体标准差与 2 倍带宽。MACD 为 12/26/9，EMA 使用 SMA 种子，柱体 = DIF − DEA；某些平台显示 2 倍柱值。RSI14 使用 Wilder 平滑。\n\n数字默认取最近已闭合线，点击形成中的线会明确标识。价格指标同属一个证据家族，不能单独宣布牛熊转换。单根突破是候选；两根闭合保持同一箱体边界，也不代表已完成回踩。");d.addView(primary(this,"刷新行情",()->refreshMarket(true)));
  LinearLayout multi=panel("把不同周期放在一起");para(multi,"每个周期独立计算，日线与小时线可以出现分歧。");for(String p:Market.PERIODS){TextView t=button(this,label(p)+" · 等待更新",false,()->{period=p;render();});multi.addView(t);gap(multi,6);periodViews.put(p,t);}LinearLayout deriv=panel("杠杆温度");TextView out=text(this,"持仓量 · OI     资金费率 · Funding",14,MUTED);deriv.addView(out);gap(deriv,12);deriv.addView(button(this,"读取 OI 与资金费",false,()->{out.setText("正在读取…");task(()->repo.derivatives(coin),j->{JSONObject oi=j.optJSONObject("oi"),f=j.optJSONObject("funding");out.setText("原生 OI  "+n(oi.optDouble("openInterest"))+" "+coin+"\n资金费  "+n(f.optDouble("lastFundingRate")*100)+"%\n下次结算  "+time(f.optLong("nextFundingTime"))+"\n来源时间  "+time(oi.optLong("time"))+"\n未做跨所汇总；美元 OI 不等同于原生 OI。");},e->out.setText("来源暂不可用："+e));}));try{Repository.Quote local=repo.localQuote(coin);showQuote(local);showBars(repo.localBars(coin,period),period);}catch(Exception ignored){}refreshMarket(true);
 }
 private void showQuote(Repository.Quote q){lastQuoteAt=q.asOf;quote.setText(n(q.price));quoteChange.setText(String.format(Locale.US,"24h  %+.2f%%",q.change));quoteChange.setTextColor(q.change>0?GREEN:q.change<0?RED:MUTED);quoteMeta.setText((q.cached?"历史快照 · ":"来源 · ")+quoteTime(q.asOf));}
 private void showBars(Repository.Bars b,String p){chart.data(b.bars,b.points);interpretation.setText(explain(b.analysis));status.setText(b.cached?"历史行情":"行情已更新");TextView selected=periodViews.get(p);if(selected!=null)selected.setText(label(p)+" · "+(b.cached?"历史 · ":"")+(b.analysis.valid()?b.analysis.trend:b.analysis.reason));}
 private void refreshMarket(boolean force){if(refreshing||tab!=0)return;refreshing=true;String c=coin,p=period;task(()->repo.bars(c,p),b->{refreshing=false;showBars(b,p);},e->{refreshing=false;status.setText("等待联网");interpretation.setText("连接暂不可用，历史行情仅供回看，暂停新信号。");});long now=System.currentTimeMillis();if(force||now-multiAt>60000){multiAt=now;for(String pp:Market.PERIODS){if(pp.equals(p))continue;TextView v=periodViews.get(pp);task(()->repo.bars(c,pp),b->{if(v!=null)v.setText(label(pp)+"  ·  "+(b.cached?"历史 · ":"")+(b.analysis.valid()?b.analysis.trend+"\n"+b.analysis.structure:b.analysis.reason));},e->{if(v!=null)v.setText(label(pp)+" · 来源不可用");});}}}
 private String explain(Market.Analysis a){if(!a.valid())return a.reason+"\n缓存与未闭合数据不产生新信号。";return a.trend+"\n"+a.structure+"\n确认时间  "+time(a.closedAt)+"\n\n"+a.candle+"；相对前收盘 "+String.format(Locale.US,"%+.2f%%",a.change)+"\n相对前 20 根成交量："+n(a.volumeRatio)+" 倍\n\nMACD · "+a.macdText+"\n\nRSI · "+a.rsiText+(a.box==null?"":"\n\n固定箱体 "+n(a.box.low)+" — "+n(a.box.high))+"\n\n价格形态不代表机制健康或个人买卖许可。";}

 private LinearLayout reportList;private void reports(){intro("研究资料","研报","保留每一期的观点、依据与反证。");chips(body,new String[]{"daily","weekly"},reportPeriod,v->{reportPeriod=v;render();});body.addView(button(this,"检查最新研究",false,()->loadReports()));gap(body,14);reportList=column(this);body.addView(reportList);loadReports();LinearLayout note=panel("研究如何更新");expand(note,"发布与更新规则","在维护观潮的项目对话里分析市场，再要求“更新”。核验并发布新一期后，应用会读取；未发布时不会自动编造日报。");}
 private void loadReports(){if(reportsRefreshing)return;reportsRefreshing=true;reportAt=System.currentTimeMillis();task(()->repo.localDocument("reports"),p->{if(reportsRefreshing&&reportList!=null&&reportList.getChildCount()==0){reports=p.data;showReports(p," · 正在检查更新");}},e->{});task(()->repo.document("reports"),p->{reportsRefreshing=false;reports=p.data;showReports(p,"");},e->{reportsRefreshing=false;if(reportList!=null&&reportList.getChildCount()==0)reportList.addView(text(this,"报告读取失败："+e,14,RED));});}
 private void showReports(Repository.Packet p,String suffix){if(reportList==null)return;reportList.removeAllViews();TextView state=text(this,p.state+suffix+" · revision "+reports.optString("revision")+(p.issue.isEmpty()?"":"\n云端请求失败："+p.issue),11,MUTED);reportList.addView(state);gap(reportList,12);JSONArray a=reports.optJSONArray("reports");if(a!=null)for(int i=a.length()-1;i>=0;i--){JSONObject r=a.optJSONObject(i);if(r==null||!r.optString("period").equals(reportPeriod))continue;LinearLayout c=card(this);c.addView(text(this,r.optString("date")+" · "+(r.optString("kind").equals("market")?"市场研究":"方法 / 使用指南"),11,MUTED));gap(c,10);c.addView(heading(this,r.optString("title"),23));gap(c,10);para(c,r.optString("summary"));String id=r.optString("id");c.addView(button(this,"打开这一期  →",false,()->{reportId=id;render();}));reportList.addView(c);}restoreScroll();}
 private JSONObject find(JSONArray a,String id){if(a!=null)for(int i=0;i<a.length();i++){JSONObject j=a.optJSONObject(i);if(j!=null&&j.optString("id").equals(id))return j;}return null;}
 private boolean has(JSONArray a,String id){if(a!=null)for(int i=0;i<a.length();i++)if(a.optString(i).equals(id))return true;return false;}
 private void reportDetail(){JSONObject r=reports==null?null:find(reports.optJSONArray("reports"),reportId);if(r==null){reportId="";reports();return;}body.addView(button(this,"← 所有研究",false,()->{reportId="";render();}));gap(body,14);intro(r.optString("edition"),r.optString("title"),r.optString("summary"));LinearLayout meta=panel("这期的适用范围");para(meta,string(r,"notice"));String until=string(r,"validUntil");if(!until.isEmpty())try{para(meta,(Instant.parse(until).toEpochMilli()<System.currentTimeMillis()?"已到复核期限 · ":"复核期限 · ")+until);}catch(Exception e){para(meta,"复核时间格式异常，暂不作为当前判断。");}para(meta,"发布时间："+(string(r,"publishedAt").isEmpty()?"方法资料，无行情发布时间":r.optString("publishedAt")));
  JSONArray take=r.optJSONArray("takeaways");if(take!=null)for(int i=0;i<take.length();i++){JSONObject t=take.optJSONObject(i);if(t!=null){LinearLayout c=panel(t.optString("title"));para(c,t.optString("text"));}}
  JSONArray sections=r.optJSONArray("sections");if(sections!=null)for(int i=0;i<sections.length();i++){JSONObject t=sections.optJSONObject(i);if(t!=null){LinearLayout c=panel(t.optString("title"));para(c,t.optString("body"));para(c,"来源 · "+t.optString("source"));}}
  JSONArray assets=r.optJSONArray("assets");if(assets!=null)for(int i=0;i<assets.length();i++){JSONObject a=assets.optJSONObject(i);if(a==null)continue;LinearLayout c=panel(a.optString("symbol"));para(c,"趋势 · "+a.optString("trend")+"\n健康 · "+a.optString("health")+"\n风险 · "+a.optString("risk"));para(c,a.optString("action"));expand(c,"证据与缺口",join(a.optJSONArray("evidence"))+"\n\n缺失\n"+join(a.optJSONArray("missing")));para(c,"失效 / 复核 · "+a.optString("invalidation")+"\n"+a.optString("nextReview"));}
  JSONArray events=reports.optJSONArray("events");if(events!=null)for(int i=0;i<events.length();i++){JSONObject e=events.optJSONObject(i);if(e==null||!has(r.optJSONArray("events"),e.optString("id")))continue;LinearLayout c=panel(e.optString("title"));para(c,e.optString("status"));para(c,e.optString("why"));expand(c,"拆开检查",join(e.optJSONArray("checklist")));JSONArray scenarios=e.optJSONArray("scenarios");if(scenarios!=null)for(int k=0;k<scenarios.length();k++){JSONObject s=scenarios.optJSONObject(k);if(s!=null)expand(c,s.optString("label")+" · "+s.optString("title"),s.optString("body")+"\n"+s.optString("watch"));}}
  LinearLayout qa=panel("就这份报告，继续理解");para(qa,"检索本期引用的解释卡。这里没有连接实时 AI，也不会编造当前市场数据。");EditText input=new EditText(this);input.setHint("例如：RSI、健康度、持仓量");input.setSingleLine(true);qa.addView(input);LinearLayout answers=column(this);JSONArray knowledge=reports.optJSONArray("knowledge");Runnable search=()->{answers.removeAllViews();String query=input.getText().toString().trim().toLowerCase(Locale.ROOT);int hits=0;if(knowledge!=null)for(int i=0;i<knowledge.length();i++){JSONObject k=knowledge.optJSONObject(i);if(k==null||!has(r.optJSONArray("qa"),k.optString("id")))continue;String searchable=k.toString().toLowerCase(Locale.ROOT);if(!query.isEmpty()&&!searchable.contains(query))continue;expand(answers,k.optString("question",k.optString("title")),k.optString("answer",k.optString("body")));hits++;}if(hits==0)para(answers,"本期没有匹配的解释。可以回到对话继续问，并要求更新。");};qa.addView(button(this,"查找解释",false,search));qa.addView(answers);search.run();LinearLayout end=panel("反证与下一步");para(end,r.optString("counterEvidence"));para(end,r.optString("nextReview"));JSONArray src=r.optJSONArray("sources");if(src!=null)for(int i=0;i<src.length();i++){JSONObject s=src.optJSONObject(i);if(s==null)continue;para(end,s.optString("title")+"\n"+s.optString("status")+"\n"+string(s,"observedAt"));link(end,"查看来源",string(s,"url"));}
 }


 private void lessons(){
  intro("基础知识","看懂关键概念","每个概念，先读一句话，再看它对市场有什么影响。");
  for(int i=0;i<catalog.length();i++){
   JSONObject item=catalog.optJSONObject(i);if(item==null)continue;
   LinearLayout c=panel(String.format(Locale.US,"%02d",i+1)+"   "+item.optString("title"));para(c,item.optString("summary"));
   c.addView(button(this,"查看解释",false,()->{lessonId=item.optString("id");render();}));
  }
 }
 private void lesson(){
  JSONObject item=find(catalog,lessonId);if(item==null){lessonId="";lessons();return;}
  body.addView(button(this,"← 所有概念",false,()->{lessonId="";render();}));gap(body,18);
  intro("基础知识",item.optString("title"),item.optString("summary"));
  para(panel("一个例子"),item.optString("example"));
  para(panel("对市场的影响"),item.optString("impact"));
  para(panel("容易误解的地方"),item.optString("caution"));
  link(panel("资料来源"),"查看原始资料",item.optString("source"));
 }

 private void flows(){
  intro("资金流向","ETF","查看每日净流入、累计变化和各基金贡献。");
  chips(body,new String[]{"BTC","ETH","SOL"},etfCoin,v->{etfCoin=v;etfLimit=30;render();});
  LinearLayout c=panel("美国现货 ETF · 每日净流");
  etfState=text(this,"正在读取历史披露…",12,MUTED);c.addView(etfState);gap(c,12);
  chips(c,new String[]{"1个月","3个月","1年","全部"},etfRange,v->{etfRange=v;etfLimit=30;drawEtf();});
  etfSummary=text(this,"",14,INK);c.addView(etfSummary);
  flowChart=new FlowChart(this);c.addView(flowChart,new LinearLayout.LayoutParams(-1,dp(this,200)));
  etfRows=column(this);c.addView(etfRows);
  c.addView(primary(this,"刷新披露数据",()->loadEtf()));
  loadEtf();
  LinearLayout explain=panel("这两个数字，先分清");para(explain,"净流入是申购减去赎回；成交量是市场上的买卖金额，两者不同。ETF 按交易日披露，通常不是秒级更新。空白表示未披露，不能当作零。");
  explain.addView(button(this,"看懂 ETF",false,()->{tab=2;lessonId="etf";render();}));
  LinearLayout pred=panel("市场正在押注什么？");para(pred,"预测市场报价与利率期货隐含定价属于不同口径。这里读取 Polymarket 活跃议题，不把报价当确定概率。");LinearLayout results=column(this);pred.addView(button(this,"读取预测市场议题",false,()->{results.removeAllViews();para(results,"正在读取…");task(()->repo.predictions(),a->{results.removeAllViews();if(a.length()==0)para(results,"当前返回列表内没有匹配议题。");for(int i=0;i<Math.min(12,a.length());i++){JSONObject m=a.optJSONObject(i);if(m==null)continue;String details=m.optString("description")+"\n截止："+m.optString("endDate")+"\n读取时间："+time(System.currentTimeMillis());try{JSONArray o=m.opt("outcomes") instanceof JSONArray?m.getJSONArray("outcomes"):new JSONArray(m.optString("outcomes"));JSONArray prices=m.opt("outcomePrices") instanceof JSONArray?m.getJSONArray("outcomePrices"):new JSONArray(m.optString("outcomePrices"));if(o.length()!=prices.length())throw new Exception();for(int k=0;k<o.length();k++){double price=prices.getDouble(k);if(!Double.isFinite(price)||price<0||price>1)throw new Exception();details+="\n"+o.getString(k)+" · 报价 "+n(price*100)+"¢";}}catch(Exception e){details+="\n报价字段不完整，不显示概率。";}expand(results,m.optString("question"),details);link(results,"核对市场与结算规则","https://polymarket.com/event/"+Uri.encode(m.optString("slug")));}},e->{results.removeAllViews();para(results,"来源不可用："+e);});}));pred.addView(results);link(pred,"CME FedWatch · 官方说明","https://www.cmegroup.com/markets/interest-rates/cme-fedwatch-tool.html");
 }

 private void alerts(){intro("消息中心","提醒","管理通知，查看检查时间和提醒记录。");LinearLayout c=panel("系统通知与后台检查");Switch enable=new Switch(this);enable.setText("启用行情与研究提醒");enable.setMinHeight(dp(this,52));enable.setChecked(prefs.getBoolean("alerts",false));c.addView(enable);enable.setOnCheckedChangeListener((b,on)->{if(on&&Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},41);enable.setChecked(false);return;}prefs.edit().putBoolean("alerts",on).putLong("enabledAt",System.currentTimeMillis()).apply();AlertJob.schedule(this);if(on)AlertJob.once(this);else WatchService.stop(this);});para(c,"通知权限："+(AlertJob.allowed(this)?"已允许":"未允许")+"\n普通后台约 15 分钟检查。开启下方实时盯盘，可在后台持续监测。");c.addView(button(this,"打开系统通知设置",false,()->openSettings(notificationSettingsIntent())));gap(c,8);
  if(Build.VERSION.SDK_INT>=28&&((ActivityManager)getSystemService(ACTIVITY_SERVICE)).isBackgroundRestricted())para(c,"系统已限制此应用的后台运行，检查可能延迟。");
  c.addView(button(this,"查看应用后台与电池设置",false,()->openAppSettings()));gap(c,8);String[][]types={{"volatility","实时盯盘 · 5 分钟内涨跌 ≥ 阈值"},{"structure","箱体突破与保持"},{"move","单根收盘涨跌 ≥ 3%"},{"indicator","MACD 交叉 / RSI 进入极值"},{"close","每根 1h / 4h 闭合"},{"report","新发布的市场研究"}};for(String[]type:types){Switch s=new Switch(this);s.setText(type[1]);s.setMinHeight(dp(this,48));s.setChecked(prefs.getBoolean("type_"+type[0],!type[0].equals("close")));s.setOnCheckedChangeListener((b,on)->prefs.edit().putBoolean("type_"+type[0],on).apply());c.addView(s);}gap(c,10);c.addView(button(this,"检查一次后台任务",false,()->Toast.makeText(this,AlertJob.once(this)?"已交给系统调度，稍后刷新记录":"请先启用提醒；如已启用，请稍后重试",Toast.LENGTH_LONG).show()));gap(c,8);c.addView(button(this,"发送本机测试通知",false,()->{if(!AlertJob.allowed(this)){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},42);else openSettings(notificationSettingsIntent());return;}String id="test:"+System.currentTimeMillis();repo.store.add(id,"观潮测试通知","设备已成功调用 Android 通知服务；不是行情信号。",System.currentTimeMillis());AlertJob.notification(this,id,"观潮测试通知","这是一条本机测试通知。");repo.store.mark(id);Toast.makeText(this,"测试通知已提交系统",Toast.LENGTH_SHORT).show();}));
  LinearLayout watch=panel("实时盯盘");para(watch,"BTC · ETH · SOL\n后台连续读取报价，监测短时波动与 1h / 4h 闭合。常驻通知显示状态，可随时停止。");
  chips(watch,new String[]{"0.5%","1%","2%","3%"},String.format(Locale.US,"%s%%",prefs.getFloat("volatilityPct",1f)==.5f?"0.5":Integer.toString((int)prefs.getFloat("volatilityPct",1f))),v->prefs.edit().putFloat("volatilityPct",Float.parseFloat(v.replace("%",""))).apply());
  para(watch,"阈值针对最近 5 分钟内的报价；同币种波动提醒至少间隔 5 分钟。行情通常每 15 秒读取，闭合约每分钟检查；网络慢时会延后。\n单次最多 6 小时，更耗电。Android 16 还限制后台同步总时长，系统可能提前停止。长期即时云推送尚未接通。");
  watch.addView(primary(this,"开启实时盯盘",()->{if(!AlertJob.allowed(this)){Toast.makeText(this,"请先允许系统通知并启用提醒",Toast.LENGTH_LONG).show();return;}if(!prefs.getBoolean("alerts",false)){prefs.edit().putBoolean("alerts",true).putLong("enabledAt",System.currentTimeMillis()).apply();AlertJob.schedule(this);}try{WatchService.start(this);Toast.makeText(this,"盯盘已启动，请查看常驻通知",Toast.LENGTH_LONG).show();}catch(RuntimeException e){Toast.makeText(this,"系统暂未允许启动，请稍后重试",Toast.LENGTH_LONG).show();}}));gap(watch,8);watch.addView(button(this,"停止实时盯盘",false,()->{WatchService.stop(this);Toast.makeText(this,"已停止实时盯盘",Toast.LENGTH_SHORT).show();}));gap(watch,12);para(watch,"最近行情响应："+time(prefs.getLong("watchResponse",0))+"\n"+prefs.getString("watchResult","尚未开启实时盯盘"));
  if(android.os.Build.MANUFACTURER.equalsIgnoreCase("vivo")||android.os.Build.MANUFACTURER.equalsIgnoreCase("iqoo"))originHelp();
  if(android.os.Build.MANUFACTURER.equalsIgnoreCase("oppo")||android.os.Build.MANUFACTURER.equalsIgnoreCase("oneplus")){LinearLayout help=panel("ColorOS 后台提醒");para(help,"在系统设置中允许通知、锁屏与横幅；查看观潮的自启动和后台耗电设置。实时盯盘开启后会有常驻通知，系统仍可能受省电策略影响。");help.addView(button(this,"查看后台设置",false,()->openAppSettings()));}
    LinearLayout log=panel("最近一次检查");para(log,"开始："+time(prefs.getLong("lastAttempt",0))+"\n来源响应："+time(prefs.getLong("lastResponse",0))+"\n六组行情检查成功："+time(prefs.getLong("lastSuccess",0))+"\n"+prefs.getString("lastResult","还没有检查记录"));log.addView(button(this,"刷新检查记录",false,()->render()));LinearLayout inbox=panel("提醒收件箱");List<String[]> notices=repo.store.notices();if(notices.isEmpty())para(inbox,"暂时没有符合条件的新事件。开启之前的旧信号不会补推。");for(String[]v:notices)expand(inbox,v[1]+" · "+time(Long.parseLong(v[3])),v[2]+"\n"+(v[4].equals("1")?"已交给系统通知服务":"仅记录，未提交系统通知"));
 }
 @Override public void onRequestPermissionsResult(int code,String[]p,int[]r){super.onRequestPermissionsResult(code,p,r);if(code==41&&r.length>0&&r[0]==PackageManager.PERMISSION_GRANTED){prefs.edit().putBoolean("alerts",true).putLong("enabledAt",System.currentTimeMillis()).apply();AlertJob.schedule(this);AlertJob.once(this);}if(tab==4)render();}

 private void refreshQuote(){
  if(!active||tab!=0||quoteRefreshing)return;
  quoteRefreshing=true;int g=generation,token=++quoteToken;String symbol=coin;
  quoteRequest=HttpRequests.submit(repo.quotes,()->{
   try{Repository.Quote q=repo.quote(symbol);main.post(()->{
    if(g!=generation||token!=quoteToken||!active||isDestroyed())return;quoteRefreshing=false;
    showQuote(q);
   });}catch(Exception e){main.post(()->{
    if(g!=generation||token!=quoteToken||!active||isDestroyed())return;quoteRefreshing=false;
    quoteMeta.setText(lastQuoteAt>0?"离线 · 历史行情\n来源："+quoteTime(lastQuoteAt):"报价暂不可用 · 请稍后重试");
   });}
  });
 }
 private void loadEtf(){
  if(etfRefreshing)return;etfRefreshing=true;etfAt=System.currentTimeMillis();String symbol=etfCoin;int request=++etfRequestGeneration;
  task(()->repo.localEtf(symbol),p->{if(request!=etfRequestGeneration)return;if(p!=null&&etfData==null){etfData=p.data;etfState.setText(p.state+" · 正在检查更新");drawEtf();}},e->{});
  task(()->repo.etfHistory(symbol),p->{
   if(request!=etfRequestGeneration)return;etfRefreshing=false;etfData=p.data;JSONArray rows=p.data.optJSONArray("rows");int count=rows==null?0:rows.length();
   String start=count==0?"—":rows.optJSONObject(0).optString("date"),end=count==0?"—":rows.optJSONObject(count-1).optString("date");
   etfState.setText(p.state+" · "+count+" 个披露日\n"+start+" 至 "+end+"\n读取时间："+p.data.optString("capturedAt")+"\n单位：百万美元 · 前台每 5 分钟检查披露"+(p.issue.isEmpty()?"":"\n更新失败，显示历史资料："+p.issue));drawEtf();
  },e->{if(request==etfRequestGeneration){etfRefreshing=false;etfState.setText("历史读取失败："+e);}});
 }
 private void drawEtf(){
  if(etfData==null||etfRows==null)return;etfRows.removeAllViews();JSONArray all=etfData.optJSONArray("rows");
  List<JSONObject> selected=new ArrayList<>();java.time.LocalDate end=java.time.LocalDate.now(java.time.ZoneOffset.UTC);
  String since=etfRange.equals("1个月")?end.minusMonths(1).toString():etfRange.equals("3个月")?end.minusMonths(3).toString():etfRange.equals("1年")?end.minusYears(1).toString():"";
  if(all!=null)for(int i=0;i<all.length();i++){JSONObject row=all.optJSONObject(i);if(row!=null&&(since.isEmpty()||row.optString("date").compareTo(since)>=0)&&row.optString("date").compareTo(end.toString())<=0)selected.add(row);}
  selected.sort((x,y)->x.optString("date").compareTo(y.optString("date")));
  double sum=0;int complete=0,partial=0;List<String>dates=new ArrayList<>();List<Double>totals=new ArrayList<>();
  for(JSONObject row:selected){dates.add(row.optString("date"));Double total=row.isNull("total")?null:row.optDouble("total",Double.NaN);totals.add(total);
   if(total!=null&&Double.isFinite(total)&&row.optString("status").equals("complete")){sum+=total;complete++;}else partial++;
  }
  etfSummary.setText(selected.isEmpty()?"所选日期范围没有披露记录。":"已完整披露累计  "+String.format(Locale.US,"%+,.1f",sum)+" 百万美元\n"+complete+" 个完整日"+(partial>0?" · "+partial+" 个未完整披露日不计入累计":""));
  flowChart.data(dates,totals);
  if(selected.isEmpty())para(etfRows,"可切换“全部”查看已有历史。数据源没有提供的日期不会补成零。");
  for(int i=selected.size()-1;i>=Math.max(0,selected.size()-etfLimit);i--){
   JSONObject row=selected.get(i);String flow=row.isNull("total")?"未披露":String.format(Locale.US,"%+,.1f",row.optDouble("total"));
   gap(etfRows,8);etfRows.addView(button(this,row.optString("date")+"     "+flow+(row.optString("status").equals("complete")?"":" · 部分"),false,()->{
    StringBuilder detail=new StringBuilder("单位：百万美元");JSONArray funds=row.optJSONArray("funds");
    if(funds!=null)for(int k=0;k<funds.length();k++){JSONObject fund=funds.optJSONObject(k);if(fund!=null)detail.append("\n").append(fund.optString("ticker")).append("   ").append(fund.isNull("flow")?"未披露":n(fund.optDouble("flow")));}
    new AlertDialog.Builder(this).setTitle(etfCoin+" · "+row.optString("date")).setMessage(detail.toString()).setPositiveButton("完成",null).show();
   }));
  }
  if(selected.size()>etfLimit){gap(etfRows,12);etfRows.addView(button(this,"加载更早记录",false,()->{etfLimit+=30;drawEtf();}));}
  gap(etfRows,12);link(etfRows,"Farside 原始披露表",etfData.optString("source"));link(etfRows,"CoinGlass 对照页",etfData.optString("compare"));restoreScroll();
 }

 private Intent notificationSettingsIntent(){return new Intent(android.provider.Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(android.provider.Settings.EXTRA_APP_PACKAGE,getPackageName());}
 private void openAppSettings(){openSettings(new Intent(android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())));}
 private void openSettings(Intent intent){try{startActivity(intent);}catch(ActivityNotFoundException|SecurityException e){Toast.makeText(this,"请在系统设置中搜索“观潮”",Toast.LENGTH_LONG).show();}}

 private void originHelp(){
   LinearLayout origin=panel("OriginOS 后台提醒");
   para(origin,"1. 允许观潮发送通知，可按需开启锁屏和横幅提醒。\n2. 在系统设置中搜索“自启动”，查看观潮的自启动权限。\n3. 在观潮的电池设置中查看是否限制了后台活动。设置入口随系统版本可能变化。");
   para(origin,"这些设置有助于后台检查；关闭 App 后的即时提醒仍需接通厂商推送。");
   origin.addView(button(this,"查看后台设置",false,()->openAppSettings()));
 }
}
