package com.tide.journal.sync;
import android.app.*;import android.app.job.*;import android.content.*;import android.content.pm.PackageManager;import android.os.Build;
import com.tide.journal.MainActivity;import com.tide.journal.R;import com.tide.journal.data.*;import com.tide.journal.domain.Market;
import org.json.*;import java.time.Instant;import java.util.concurrent.*;

public final class AlertJob extends JobService {
 private static final ExecutorService EXECUTOR=Executors.newSingleThreadExecutor();private final ConcurrentHashMap<Integer,Run>runs=new ConcurrentHashMap<>();
 private static final class Run{volatile boolean cancelled;Future<?>future;}
 public static SharedPreferences prefs(Context c){return c.getSharedPreferences("native-settings",0);}
 public static void channel(Context c){c.getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel("market-alerts","行情与研究",NotificationManager.IMPORTANCE_HIGH));}
 public static boolean allowed(Context c){NotificationManager m=c.getSystemService(NotificationManager.class);NotificationChannel channel=m.getNotificationChannel("market-alerts");return(Build.VERSION.SDK_INT<33||c.checkSelfPermission("android.permission.POST_NOTIFICATIONS")==PackageManager.PERMISSION_GRANTED)&&m.areNotificationsEnabled()&&(channel==null||channel.getImportance()!=NotificationManager.IMPORTANCE_NONE);}
 public static void schedule(Context c){JobScheduler s=c.getSystemService(JobScheduler.class);s.cancel(510);s.cancel(511);if(!prefs(c).getBoolean("alerts",false)){s.cancel(610);s.cancel(611);return;}if(s.getPendingJob(610)!=null)return;int r=s.schedule(new JobInfo.Builder(610,new ComponentName(c,AlertJob.class)).setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY).setPersisted(true).setPeriodic(15*60*1000L).build());if(r!=JobScheduler.RESULT_SUCCESS)prefs(c).edit().putString("lastResult","系统未接受后台检查任务").apply();}
 public static boolean once(Context c){if(!prefs(c).getBoolean("alerts",false))return false;JobScheduler scheduler=c.getSystemService(JobScheduler.class);if(scheduler.getPendingJob(611)!=null)return true;boolean accepted=scheduler.schedule(new JobInfo.Builder(611,new ComponentName(c,AlertJob.class)).setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY).setMinimumLatency(0).build())==JobScheduler.RESULT_SUCCESS;if(!accepted)prefs(c).edit().putString("lastResult","系统暂未接受单次检查，请稍后重试").apply();return accepted;}
 public static void notification(Context c,String id,String title,String detail){channel(c);Intent i=new Intent(c,MainActivity.class).putExtra("tab",4).setFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);PendingIntent pi=PendingIntent.getActivity(c,0,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new Notification.Builder(c,"market-alerts").setSmallIcon(R.drawable.notification).setContentTitle(title).setContentText(detail).setStyle(new Notification.BigTextStyle().bigText(detail)).setContentIntent(pi).setCategory(Notification.CATEGORY_EVENT).setVisibility(Notification.VISIBILITY_PRIVATE).setAutoCancel(true).build();c.getSystemService(NotificationManager.class).notify(id,0,n);}
 @Override public boolean onStartJob(JobParameters p){Run r=new Run();Run old=runs.put(p.getJobId(),r);if(old!=null){old.cancelled=true;if(old.future!=null)old.future.cancel(true);}r.future=HttpRequests.submit(EXECUTOR,()->{try{check(r);}catch(Exception e){if(enabled(r))prefs(this).edit().putString("lastResult","后台检查失败："+(e.getMessage()==null?e.getClass().getSimpleName():e.getMessage())).apply();}finally{if(runs.remove(p.getJobId(),r)&&!r.cancelled)jobFinished(p,false);}});return true;}
 @Override public boolean onStopJob(JobParameters p){Run r=runs.remove(p.getJobId());if(r!=null){r.cancelled=true;if(r.future!=null)r.future.cancel(true);}return prefs(this).getBoolean("alerts",false);}
 private boolean enabled(Run r){return!r.cancelled&&!Thread.currentThread().isInterrupted()&&prefs(this).getBoolean("alerts",false);}
 private void check(Run r){SignalChecks.check(this,()->enabled(r));}
}
