package com.tide.journal.sync;
import android.app.*;import android.app.job.*;import android.content.*;import android.content.pm.PackageManager;import android.os.Build;
import com.tide.journal.MainActivity;import com.tide.journal.R;import com.tide.journal.data.*;import com.tide.journal.domain.Market;
import org.json.*;import java.time.Instant;import java.util.concurrent.*;

public final class AlertJob extends JobService {
 private static final ExecutorService EXECUTOR=Executors.newSingleThreadExecutor();private final ConcurrentHashMap<Integer,Run>runs=new ConcurrentHashMap<>();
 private static final class Run{volatile boolean cancelled;Future<?>future;}
 public static SharedPreferences prefs(Context c){return c.getSharedPreferences("native-settings",0);}
 public static void channel(Context c){c.getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel("native-signals","行情与研究",NotificationManager.IMPORTANCE_DEFAULT));}
 public static boolean allowed(Context c){return(Build.VERSION.SDK_INT<33||c.checkSelfPermission("android.permission.POST_NOTIFICATIONS")==PackageManager.PERMISSION_GRANTED)&&c.getSystemService(NotificationManager.class).areNotificationsEnabled();}
 public static void schedule(Context c){JobScheduler s=c.getSystemService(JobScheduler.class);s.cancel(510);s.cancel(511);if(!prefs(c).getBoolean("alerts",false)){s.cancel(610);s.cancel(611);return;}if(s.getPendingJob(610)!=null)return;int r=s.schedule(new JobInfo.Builder(610,new ComponentName(c,AlertJob.class)).setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY).setPersisted(true).setPeriodic(15*60*1000L).build());if(r!=JobScheduler.RESULT_SUCCESS)prefs(c).edit().putString("lastResult","系统未接受后台检查任务").apply();}
 public static boolean once(Context c){if(!prefs(c).getBoolean("alerts",false))return false;return c.getSystemService(JobScheduler.class).schedule(new JobInfo.Builder(611,new ComponentName(c,AlertJob.class)).setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY).setMinimumLatency(0).build())==JobScheduler.RESULT_SUCCESS;}
 public static void notification(Context c,String id,String title,String detail){channel(c);Intent i=new Intent(c,MainActivity.class).putExtra("tab",4).setFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);PendingIntent pi=PendingIntent.getActivity(c,0,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new Notification.Builder(c,"native-signals").setSmallIcon(R.drawable.notification).setContentTitle(title).setContentText(detail).setStyle(new Notification.BigTextStyle().bigText(detail)).setContentIntent(pi).setAutoCancel(true).build();c.getSystemService(NotificationManager.class).notify(id,0,n);}
 @Override public boolean onStartJob(JobParameters p){Run r=new Run();Run old=runs.put(p.getJobId(),r);if(old!=null){old.cancelled=true;if(old.future!=null)old.future.cancel(true);}r.future=EXECUTOR.submit(()->{try{check(r);}finally{if(runs.remove(p.getJobId(),r)&&!r.cancelled)jobFinished(p,false);}});return true;}
 @Override public boolean onStopJob(JobParameters p){Run r=runs.remove(p.getJobId());if(r!=null){r.cancelled=true;if(r.future!=null)r.future.cancel(true);}return prefs(this).getBoolean("alerts",false);}
 private boolean enabled(Run r){return!r.cancelled&&!Thread.currentThread().isInterrupted()&&prefs(this).getBoolean("alerts",false);}
 private void check(Run r){if(!enabled(r))return;SharedPreferences p=prefs(this);Repository repo=Repository.get(this);long now=System.currentTimeMillis();p.edit().putLong("lastAttempt",now).apply();int valid=0;String issue="";
  for(String coin:new String[]{"BTC","ETH","SOL"})for(String period:new String[]{"1h","4h"}){if(!enabled(r))return;try{Repository.Bars b=repo.bars(coin,period);p.edit().putLong("lastResponse",System.currentTimeMillis()).apply();Market.Analysis a=b.analysis;if(!a.valid()){issue=a.reason;continue;}valid++;for(Market.Event e:a.events)deliver(r,repo,coin+":"+e.id,coin+" "+period+" · "+e.title,e.detail,e.at,e.type);deliver(r,repo,coin+":"+period+":"+a.closedAt+":close",coin+" "+period+" 已闭合",a.trend+"；"+a.structure,a.closedAt,"close");}catch(Exception e){issue=e.getMessage();}}
  if(enabled(r)&&p.getBoolean("type_report",true))try{Repository.Packet pack=repo.document("reports");if(!pack.state.equals("云端已读取")){issue="研究云端读取失败："+pack.issue;}else{JSONArray rows=pack.data.getJSONArray("reports");for(int i=0;i<rows.length();i++){JSONObject report=rows.getJSONObject(i);if(report.optString("kind").equals("market"))deliver(r,repo,"report:"+report.getString("id"),report.getString("title"),report.getString("summary"),Instant.parse(report.getString("publishedAt")).toEpochMilli(),"report");}}}catch(Exception e){issue=e.getMessage();}
  if(enabled(r)){SharedPreferences.Editor e=p.edit().putString("lastResult","行情有效覆盖 "+valid+"/6"+(issue.isEmpty()?"":" · "+issue));if(valid==6)e.putLong("lastSuccess",System.currentTimeMillis());e.apply();}
 }
 private void deliver(Run r,Repository repo,String id,String title,String body,long at,String type){long now=System.currentTimeMillis();SharedPreferences p=prefs(this);if(!enabled(r)||!p.getBoolean("type_"+type,!type.equals("close"))||at<p.getLong("enabledAt",now)||at>now||now-at>86400000)return;repo.store.add(id,title,body,at);if(enabled(r)&&!repo.store.sent(id)&&allowed(this)){notification(this,id,title,body);repo.store.mark(id);}}
}
