package com.tide.journal.ui;
import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;
public final class Ui {
 public static final int BG=0xfff4f5f1,INK=0xff15352f,MUTED=0xff637770,GREEN=0xff19836a,RED=0xffbd5b59,LINE=0xffe1e7df,BLUE=0xff6688b5;
 public static int dp(Context c,float n){return Math.round(n*c.getResources().getDisplayMetrics().density);}public static GradientDrawable shape(int color,float r,Context c){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(c,r));return d;}
 public static LinearLayout column(Context c){LinearLayout l=new LinearLayout(c);l.setOrientation(1);return l;}public static LinearLayout row(Context c){LinearLayout l=new LinearLayout(c);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 public static TextView text(Context c,String s,float size,int color){TextView t=new TextView(c);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setFontFeatureSettings("tnum");t.setLineSpacing(dp(c,3),1);return t;}public static TextView heading(Context c,String s,int size){TextView t=text(c,s,size,INK);t.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));return t;}
 public static TextView button(Context c,String s,boolean selected,Runnable click){TextView t=text(c,s,14,selected?-1:INK);t.setGravity(Gravity.CENTER);t.setMinHeight(dp(c,48));t.setPadding(dp(c,14),dp(c,8),dp(c,14),dp(c,8));t.setBackground(new RippleDrawable(android.content.res.ColorStateList.valueOf(0x2219836a),shape(selected?INK:0xffe9eee6,16,c),null));t.setOnClickListener(v->{v.performHapticFeedback(HapticFeedbackConstants.CLOCK_TICK);click.run();});t.setFocusable(true);t.setContentDescription(s);return t;}
 public static LinearLayout card(Context c){LinearLayout l=column(c);l.setPadding(dp(c,20),dp(c,20),dp(c,20),dp(c,20));GradientDrawable b=shape(0xfffefefa,24,c);b.setStroke(dp(c,1),LINE);l.setBackground(b);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(c,14);l.setLayoutParams(p);return l;}
 public static void gap(LinearLayout l,int h){l.addView(new Space(l.getContext()),new LinearLayout.LayoutParams(1,dp(l.getContext(),h)));}public static void weighted(LinearLayout row,View c){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(row.getContext(),3),0,dp(row.getContext(),3),0);row.addView(c,p);}
 public static String n(double x){return Double.isFinite(x)?String.format(java.util.Locale.US,Math.abs(x)>=1000?"%,.2f":"%.3f",x):"—";}public static String time(long t){return t<=0?"尚无成功记录":java.time.Instant.ofEpochMilli(t).atZone(java.time.ZoneOffset.UTC).format(java.time.format.DateTimeFormatter.ofPattern("MM-dd HH:mm 'UTC'"));}
}
