package com.tide.journal.ui;
import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;
public final class Ui {
 public static final int BG=0xfff2f2f7,INK=0xff1c1c1e,MUTED=0xff636366,GREEN=0xff248a3d,RED=0xffd74242,LINE=0xffe5e5ea,BLUE=0xff007aff;
 public static int dp(Context c,float n){return Math.round(n*c.getResources().getDisplayMetrics().density);}public static GradientDrawable shape(int color,float r,Context c){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(c,r));return d;}
 public static LinearLayout column(Context c){LinearLayout l=new LinearLayout(c);l.setOrientation(1);return l;}public static LinearLayout row(Context c){LinearLayout l=new LinearLayout(c);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 public static TextView text(Context c,String s,float size,int color){TextView t=new TextView(c);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setFontFeatureSettings("tnum");t.setLineSpacing(dp(c,3),1);return t;}public static TextView heading(Context c,String s,int size){TextView t=text(c,s,size,INK);t.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));return t;}
 public static TextView button(Context c,String s,boolean selected,Runnable click){TextView t=text(c,s,14,selected?-1:INK);t.setGravity(Gravity.CENTER);t.setMinHeight(dp(c,48));t.setPadding(dp(c,14),dp(c,8),dp(c,14),dp(c,8));selectButton(t,selected);t.setOnClickListener(v->{v.performHapticFeedback(HapticFeedbackConstants.CLOCK_TICK);click.run();});t.setFocusable(true);t.setContentDescription(s);return t;}
 public static void selectButton(TextView t,boolean selected){t.setSelected(selected);t.setTextColor(selected?Color.WHITE:INK);t.setBackground(new RippleDrawable(android.content.res.ColorStateList.valueOf(0x22007aff),shape(selected?BLUE:0xffe9e9ef,12,t.getContext()),null));}
 public static String quoteTime(long t){return t<=0?"尚无报价":java.time.Instant.ofEpochMilli(t).atZone(java.time.ZoneOffset.UTC).format(java.time.format.DateTimeFormatter.ofPattern("MM-dd HH:mm:ss 'UTC'"));}
 public static LinearLayout card(Context c){LinearLayout l=column(c);l.setPadding(dp(c,20),dp(c,20),dp(c,20),dp(c,20));GradientDrawable b=shape(Color.WHITE,18,c);b.setStroke(dp(c,1),0xffededf2);l.setBackground(b);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(c,14);l.setLayoutParams(p);return l;}
 public static void gap(LinearLayout l,int h){l.addView(new Space(l.getContext()),new LinearLayout.LayoutParams(1,dp(l.getContext(),h)));}public static void weighted(LinearLayout row,View c){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(row.getContext(),3),0,dp(row.getContext(),3),0);row.addView(c,p);}
 public static String n(double x){return Double.isFinite(x)?String.format(java.util.Locale.US,Math.abs(x)>=1000?"%,.2f":"%.3f",x):"—";}public static String time(long t){return t<=0?"尚无成功记录":java.time.Instant.ofEpochMilli(t).atZone(java.time.ZoneOffset.UTC).format(java.time.format.DateTimeFormatter.ofPattern("MM-dd HH:mm 'UTC'"));}
}
