import com.tide.journal.domain.*;import java.util.*;import java.nio.file.*;import java.time.Instant;
public final class DomainTest {
 static int assertions;static void check(boolean v,String message){assertions++;if(!v)throw new AssertionError(message);}static void near(double a,double b,String label){check(Double.isNaN(a)&&Double.isNaN(b)||Math.abs(a-b)<1e-8,label+": "+a+" != "+b);}
 static void reject(Runnable r){try{r.run();throw new AssertionError("Expected rejection");}catch(IllegalArgumentException ok){assertions++;}}
 static Market.Bar bar(long t,long size,double o,double h,double l,double c,double v,boolean closed){return new Market.Bar(t,t+size-1,o,h,l,c,v,closed);}
 public static void main(String[]args)throws Exception{long now=Instant.parse("2026-09-20T05:22:00Z").toEpochMilli();List<String>lines=Files.readAllLines(Paths.get("tests/indicator-reference.csv"));String[]meta=lines.get(1).substring(2).split(",");List<double[]>rows=new ArrayList<>();for(String l:lines)if(!l.startsWith("#")){String[]f=l.split(",");double[]v=new double[f.length];for(int i=0;i<f.length;i++)v[i]=Double.parseDouble(f[i]);rows.add(v);}
  for(String p:Market.PERIODS){long size=Market.duration(p),base=Market.boundary(p,now)-rows.size()*size;List<Market.Bar>b=new ArrayList<>();for(int i=0;i<rows.size();i++){double[]r=rows.get(i);b.add(bar(base+i*size,size,r[0],r[1],r[2],r[3],r[4],true));}List<Market.Point>points=Market.indicators(b);for(int i=0;i<points.size();i++){Market.Point q=points.get(i);double[]actual={q.middle,q.upper,q.lower,q.dif,q.dea,q.hist,q.rsi};for(int k=0;k<7;k++)near(actual[k],rows.get(i)[k+5],p+" row "+i+" indicator "+k);}Market.Analysis a=Market.analyze(b,p,now);check(a.valid(),p+" valid");check(a.code.equals(meta[0]),"structure parity");check(a.trend.equals(meta[1]),"trend parity");check(!Market.analyze(b,p,now+size).valid(),"stale");List<Market.Bar>gap=new ArrayList<>(b);gap.remove(gap.size()-20);check(Market.analyze(gap,p,now).quality.equals("warming"),"gap warms");List<Market.Bar>dup=new ArrayList<>(b);dup.add(b.get(b.size()-1));reject(()->Market.analyze(dup,p,now));Market.Bar last=b.get(b.size()-1);b.set(b.size()-1,bar(last.openAt,size,last.open,last.high,last.low,last.close,last.volume,false));check(!Market.analyze(b,p,now).valid(),"forming cannot confirm");List<Market.Bar>flat=new ArrayList<>();for(int i=0;i<90;i++)flat.add(bar(base+i*size,size,100,100,100,100,0,true));Market.Analysis f=Market.analyze(flat,p,now);check(f.valid(),"flat valid");check(Double.isNaN(f.point.rsi)&&Double.isNaN(f.volumeRatio),"flat avoids false precision");check(f.events.isEmpty(),"flat no alerts");}
  check(Instant.ofEpochMilli(Market.boundary("1w",now)).atZone(java.time.ZoneOffset.UTC).getDayOfWeek()==java.time.DayOfWeek.MONDAY,"UTC Monday week");
  // Both confirmation bars must use the same historical box. A reversal through its other edge is failure.
  long size=Market.duration("4h"),base=Market.boundary("4h",now)-92*size;List<Market.Bar>b=new ArrayList<>();for(int i=0;i<90;i++){double c=i%2==0?99.6:100.4;b.add(bar(base+i*size,size,100,101,99,c,100,true));}b.add(bar(base+90*size,size,102,103,101.5,102.5,100,true));b.add(bar(base+91*size,size,102.5,104,102,103,100,true));Market.Analysis held=Market.analyze(b,"4h",now);check(held.code.equals("held-up"),"two bars fixed box held up");near(held.box.high,101,"fixed original box");b.set(91,bar(base+91*size,size,102,103,97,98,100,true));check(Market.analyze(b,"4h",now).code.equals("failed-through-down"),"reversal through box");
  near(Lessons.calculate("rates",3).values[2],0,"rate zero");near(Lessons.calculate("cuts",1).values[2],-600,"cut negative");near(Lessons.calculate("inflation",20).values[1],16,"whole goods");near(Lessons.calculate("supply",20).values[2],0,"zero shortage");near(Lessons.calculate("jobs",10).values[1],0,"zero unemployed");check(Lessons.calculate("jobs",5).formula.contains("5.26%"),"changing denominator");near(Lessons.calculate("etf",0).values[2],-200,"ETF negative");near(Lessons.calculate("etf",200).values[2],0,"ETF zero");near(Lessons.calculate("expectations",0).values[2],-25,"dovish surprise");near(Lessons.calculate("expectations",50).values[2],25,"hawkish surprise");near(Lessons.calculate("oi",50).values[0],100,"native OI fixed");near(Lessons.calculate("leverage",5).values[2],50,"leverage equity");reject(()->Lessons.calculate("jobs",.5));reject(()->Lessons.calculate("supply",.1));reject(()->Lessons.calculate("rates",Double.NaN));reject(()->Lessons.calculate("leverage",6));
  System.out.println("PASS "+assertions+" assertions: six periods, independent indicator fixtures, stale/gap/closed gates, fixed-box reversal, nine teaching models");
 }
}
