package com.tide.journal.domain;
import java.util.*;
public final class Market {
 public static final String[] PERIODS={"1h","4h","8h","12h","1d","1w"};
 public static long duration(String p){switch(p){case "1h":return 3600000L;case "4h":return 14400000L;case "8h":return 28800000L;case "12h":return 43200000L;case "1d":return 86400000L;case "1w":return 604800000L;default:throw new IllegalArgumentException("周期不支持");}}
 public static long boundary(String p,long now){long anchor=p.equals("1w")?345600000L:0;return Math.floorDiv(now-anchor,duration(p))*duration(p)+anchor;}
 public static final class Bar {public final long openAt,closeAt;public final double open,high,low,close,volume;public final boolean closed;public Bar(long t,long end,double o,double h,double l,double c,double v,boolean x){openAt=t;closeAt=end;open=o;high=h;low=l;close=c;volume=v;closed=x;}}
 public static final class Point {public double middle=Double.NaN,upper=Double.NaN,lower=Double.NaN,dif=Double.NaN,dea=Double.NaN,hist=Double.NaN,rsi=Double.NaN,atr=Double.NaN;}
 private static final class Ema {final int n;int count;double sum,value=Double.NaN;Ema(int n){this.n=n;}double add(double v){if(Double.isNaN(value)){sum+=v;if(++count==n)value=sum/n;}else value+=2.0/(n+1)*(v-value);return value;}}
 public static List<Point> indicators(List<Bar> bars){List<Point> out=new ArrayList<>();List<Double> win=new ArrayList<>();Ema fast=new Ema(12),slow=new Ema(26),signal=new Ema(9);Bar prev=null;int deltas=0,trCount=0;double gain=0,loss=0,atr=Double.NaN,trSum=0;
  for(Bar b:bars){if(prev!=null&&(prev.closeAt+1!=b.openAt||!prev.closed)){win.clear();fast=new Ema(12);slow=new Ema(26);signal=new Ema(9);prev=null;deltas=0;gain=loss=trSum=0;trCount=0;atr=Double.NaN;}if(!Double.isFinite(b.close)||b.close<=0)throw new IllegalArgumentException("收盘无效");Point p=new Point();win.add(b.close);if(win.size()>20)win.remove(0);if(win.size()==20){double m=0;for(double x:win)m+=x/20;double v=0;for(double x:win)v+=(x-m)*(x-m)/20;p.middle=m;p.upper=m+2*Math.sqrt(v);p.lower=m-2*Math.sqrt(v);}double f=fast.add(b.close),s=slow.add(b.close);if(Double.isFinite(f)&&Double.isFinite(s)){p.dif=f-s;p.dea=signal.add(p.dif);p.hist=p.dif-p.dea;}if(prev!=null){double d=b.close-prev.close;deltas++;if(deltas<=14){gain+=Math.max(d,0)/14;loss+=Math.max(-d,0)/14;}else{gain=(13*gain+Math.max(d,0))/14;loss=(13*loss+Math.max(-d,0))/14;}}if(deltas>=14&&(gain!=0||loss!=0))p.rsi=loss==0?100:gain==0?0:100-100/(1+gain/loss);double tr=prev==null?b.high-b.low:Math.max(b.high-b.low,Math.max(Math.abs(b.high-prev.close),Math.abs(b.low-prev.close)));if(++trCount<=14){trSum+=tr;if(trCount==14)atr=trSum/14;}else atr=(13*atr+tr)/14;p.atr=atr;out.add(p);prev=b;}return out;
 }
 public static final class Box {public double high,low,atr;Box(double h,double l,double a){high=h;low=l;atr=a;}}
 private static Box box(List<Bar>b,int from,int end,double atr){if(end-from!=20||!Double.isFinite(atr)||atr<=0)return null;double hi=-Double.MAX_VALUE,lo=Double.MAX_VALUE,path=0;for(int i=from;i<end;i++){hi=Math.max(hi,b.get(i).high);lo=Math.min(lo,b.get(i).low);if(i>from)path+=Math.abs(b.get(i).close-b.get(i-1).close);}double w=hi-lo,eff=path==0?0:Math.abs(b.get(end-1).close-b.get(from).close)/path;int top=0,bottom=0;for(int i=from;i<end;i++){if(b.get(i).high>=hi-w*.15)top++;if(b.get(i).low<=lo+w*.15)bottom++;}return w>0&&w<=8*atr&&eff<=.35&&top>=2&&bottom>=2?new Box(hi,lo,atr):null;}
 public static final class Event {public final String id,type,title,detail;public final long at;public Event(String id,String type,String title,String detail,long at){this.id=id;this.type=type;this.title=title;this.detail=detail;this.at=at;}}
 public static final class Analysis {public String quality="missing",reason="没有已闭合数据",period,trend="",structure="尚无合格箱体",code="unclassified",macdText="",rsiText="",candle="";public long closedAt;public double close,change,sma20,sma50,volumeRatio=Double.NaN;public Point point;public Box box;public final List<Event> events=new ArrayList<>();public boolean valid(){return quality.equals("valid");}}
 private static double mean(List<Bar>b,int from,int end){double sum=0;for(int i=from;i<end;i++)sum+=b.get(i).close;return sum/(end-from);}
 public static Analysis analyze(List<Bar> input,String period,long now){long size=duration(period);Analysis a=new Analysis();a.period=period;List<Bar>b=new ArrayList<>();long previous=-1;int start=0;
  for(Bar x:input){if(x.openAt<=previous)throw new IllegalArgumentException("K线重复或乱序");previous=x.openAt;if(!Double.isFinite(x.open)||!Double.isFinite(x.high)||!Double.isFinite(x.low)||!Double.isFinite(x.close)||!Double.isFinite(x.volume)||x.low<=0||x.low>Math.min(x.open,x.close)||x.high<Math.max(x.open,x.close)||x.volume<0||x.closeAt-x.openAt!=size-1||boundary(period,x.openAt)!=x.openAt)throw new IllegalArgumentException("K线口径不一致");if(x.closed&&x.closeAt<now){if(!b.isEmpty()&&b.get(b.size()-1).closeAt+1!=x.openAt)start=b.size();b.add(x);}}
  if(b.isEmpty())return a;Bar last=b.get(b.size()-1);if(last.closeAt!=boundary(period,now)-1){a.quality="stale";a.reason="最新闭合未到齐，暂停判读";return a;}b=new ArrayList<>(b.subList(start,b.size()));int n=b.size();if(n<55){a.quality="warming";a.reason="连续闭合不足55根，重新预热";return a;}List<Point> points=indicators(b);Point cur=points.get(n-1),prev=points.get(n-2);Bar before=b.get(n-2);a.point=cur;a.close=last.close;a.closedAt=last.closeAt+1;a.change=(last.close/before.close-1)*100;a.sma20=mean(b,n-20,n);a.sma50=mean(b,n-50,n);double slope=a.sma20-mean(b,n-25,n-5);a.trend=last.close>a.sma20&&a.sma20>a.sma50&&slope>0?"价格偏强候选":last.close<a.sma20&&a.sma20<a.sma50&&slope<0?"价格偏弱候选":"价格方向分歧";
  Box f=box(b,n-22,n-2,points.get(n-3).atr);if(f!=null&&before.close>f.high+.1*f.atr){if(last.close>f.high+.1*f.atr){a.code="held-up";a.structure="两根收盘保持箱顶上方";}else if(last.close<=f.high){a.code=last.close<f.low?"failed-through-down":"failed-up";a.structure=last.close<f.low?"突破后反向失守原箱底":"突破后收回箱体";}}if(f!=null&&before.close<f.low-.1*f.atr){if(last.close<f.low-.1*f.atr){a.code="held-down";a.structure="两根收盘保持箱底下方";}else if(last.close>=f.low){a.code=last.close>f.high?"failed-through-up":"failed-down";a.structure=last.close>f.high?"跌破后反向越过原箱顶":"跌破后收回箱体";}}
  if(a.code.equals("unclassified")){f=box(b,n-21,n-1,points.get(n-2).atr);if(f!=null){a.code=last.close>f.high+.1*f.atr?"break-up":last.close<f.low-.1*f.atr?"break-down":"range";a.structure=a.code.equals("break-up")?"单根向上突破候选":a.code.equals("break-down")?"单根向下跌破候选":"箱体附近震荡候选";}}a.box=f;String cross=prev.hist<=0&&cur.hist>0?"金叉候选":prev.hist>=0&&cur.hist<0?"死叉候选":null;
  a.macdText=(cross==null?"本根没有新的交叉":cross)+"；DIF "+(cur.dif>=0?"在零轴上方":"在零轴下方")+"，柱体"+(Math.abs(cur.hist)>Math.abs(prev.hist)?"绝对值扩大":"收缩或持平")+"。动量不能独立决定买卖。";a.rsiText=Double.isNaN(cur.rsi)?"收盘没有变化，RSI 不报伪精确值。":cur.rsi>=70?"上涨力度较强，高位可以持续；不等于应该卖出。":cur.rsi<=30?"下跌力度较强，低位可以持续；不等于应该买入。":"处于30–70常用区间，只描述力度，不确认牛熊转换。";
  double body=Math.abs(last.close-last.open),span=last.high-last.low,up=last.high-Math.max(last.open,last.close),down=Math.min(last.open,last.close)-last.low;a.candle=span==0?"本根没有振幅":body/span<.1?"小实体／十字形":up>2*body&&up>span*.4?"上影较长：高位回吐":down>2*body&&down>span*.4?"下影较长：低位回收":last.close>=last.open?"阳线：收盘高于开盘":"阴线：收盘低于开盘";double volume=0;for(int i=n-21;i<n-1;i++)volume+=b.get(i).volume/20;if(volume>0)a.volumeRatio=last.volume/volume;String id=period+":"+last.closeAt+":";if(!a.code.equals("range")&&!a.code.equals("unclassified"))a.events.add(new Event(id+"structure","structure",a.structure,"固定前序箱体；健康度仍需现货与资金证据。",a.closedAt));if(cross!=null)a.events.add(new Event(id+"macd-cross","indicator","MACD "+cross,a.macdText,a.closedAt));if(Double.isFinite(cur.rsi)&&Double.isFinite(prev.rsi)&&((cur.rsi>=70&&prev.rsi<70)||(cur.rsi<=30&&prev.rsi>30)))a.events.add(new Event(id+"rsi-extreme","indicator","RSI 进入常用极值区",a.rsiText,a.closedAt));if(Math.abs(a.change)>=3)a.events.add(new Event(id+"move","move",String.format(Locale.US,"收盘涨跌 %+.2f%%",a.change),"相对前根闭合收盘，阈值3%。",a.closedAt));a.quality="valid";a.reason="已闭合／Binance现货／USDT／UTC";return a;
 }
}
