plugins { id 'com.android.application' }
android {
 namespace 'com.tide.journal'
 compileSdk 36
 defaultConfig { applicationId 'com.guanchao.app'; minSdk 26; targetSdk 36; versionCode 9; versionName '0.9' }
 compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
 buildTypes { release { minifyEnabled false } }
}
